//! Bulk operations for CostCenter entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCostCenterDto;
use crate::application::service::CostCenterService;
use crate::domain::entity::CostCenter;

/// Bulk operation handler for CostCenter entities.
///
/// Wraps `CostCenterService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CostCenterBulkService = GenericBulkService<CostCenter, CreateCostCenterDto, CostCenterService>;

// <<< CUSTOM
// END CUSTOM
