//! Bulk operations for FinancialStatement entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateFinancialStatementDto;
use crate::application::service::FinancialStatementService;
use crate::domain::entity::FinancialStatement;

/// Bulk operation handler for FinancialStatement entities.
///
/// Wraps `FinancialStatementService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type FinancialStatementBulkService = GenericBulkService<FinancialStatement, CreateFinancialStatementDto, FinancialStatementService>;

// <<< CUSTOM
// END CUSTOM
