//! Bulk operations for Journal entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateJournalDto;
use crate::application::service::JournalService;
use crate::domain::entity::Journal;

/// Bulk operation handler for Journal entities.
///
/// Wraps `JournalService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type JournalBulkService = GenericBulkService<Journal, CreateJournalDto, JournalService>;

// <<< CUSTOM
// END CUSTOM
