//! Bulk operations
//!
//! Generated by backbone-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod account_bulk;
pub mod accounting_post_bulk;
pub mod financial_statement_bulk;
pub mod fiscal_period_bulk;
pub mod journal_bulk;
pub mod journal_line_bulk;
pub mod ledger_bulk;
pub mod reconciliation_bulk;
pub mod reconciliation_item_bulk;

pub use account_bulk::AccountBulkService;
pub use accounting_post_bulk::AccountingPostBulkService;
pub use financial_statement_bulk::FinancialStatementBulkService;
pub use fiscal_period_bulk::FiscalPeriodBulkService;
pub use journal_bulk::JournalBulkService;
pub use journal_line_bulk::JournalLineBulkService;
pub use ledger_bulk::LedgerBulkService;
pub use reconciliation_bulk::ReconciliationBulkService;
pub use reconciliation_item_bulk::ReconciliationItemBulkService;

// <<< CUSTOM
// END CUSTOM
