//! Bulk operations for ReconciliationItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateReconciliationItemDto;
use crate::application::service::ReconciliationItemService;
use crate::domain::entity::ReconciliationItem;

/// Bulk operation handler for ReconciliationItem entities.
///
/// Wraps `ReconciliationItemService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ReconciliationItemBulkService = GenericBulkService<ReconciliationItem, CreateReconciliationItemDto, ReconciliationItemService>;

// <<< CUSTOM
// END CUSTOM
