//! JournalLine DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::JournalLine;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new JournalLine
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateJournalLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub journal_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub line_number: i32,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub account_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub account_number: String,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub account_name: String,
    pub debit_amount: Decimal,
    pub credit_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub exchange_rate: Decimal,
    pub base_debit_amount: Decimal,
    pub base_credit_amount: Decimal,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_center: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_reference: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_tax_line: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tax_rate: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tax_base_amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub related_line_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub has_quantity: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unit_price: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_reconciled: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reconciliation_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reconciled_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_posted: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ledger_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub posted_at: Option<DateTime<Utc>>,
    pub tags: serde_json::Value,
    pub data: serde_json::Value,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a JournalLine
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateJournalLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub journal_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub line_number: i32,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub account_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub account_number: String,
    #[cfg_attr(feature = "validation", validate(length(max = 100)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub account_name: String,
    pub debit_amount: Decimal,
    pub credit_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub exchange_rate: Decimal,
    pub base_debit_amount: Decimal,
    pub base_credit_amount: Decimal,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_center: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_reference: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_tax_line: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tax_rate: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tax_base_amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub related_line_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub has_quantity: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unit_price: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_reconciled: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reconciliation_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reconciled_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_posted: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ledger_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub posted_at: Option<DateTime<Utc>>,
    pub tags: serde_json::Value,
    pub data: serde_json::Value,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a JournalLine
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchJournalLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub journal_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line_number: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_number: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub debit_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credit_amount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exchange_rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base_debit_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base_credit_amount: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost_center: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_reference: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_tax_line: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_base_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub related_line_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub has_quantity: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit_price: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_reconciled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reconciliation_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reconciled_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_posted: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ledger_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub posted_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl PatchJournalLineDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.journal_id.is_some() || self.provider_id.is_some() || self.outlet_id.is_some() || self.line_number.is_some() || self.account_id.is_some() || self.account_number.is_some() || self.account_name.is_some() || self.debit_amount.is_some() || self.credit_amount.is_some() || self.currency.is_some() || self.exchange_rate.is_some() || self.base_debit_amount.is_some() || self.base_credit_amount.is_some() || self.description.is_some() || self.cost_center.is_some() || self.project.is_some() || self.department.is_some() || self.source_type.is_some() || self.source_id.is_some() || self.source_reference.is_some() || self.is_tax_line.is_some() || self.tax_rate.is_some() || self.tax_base_amount.is_some() || self.related_line_id.is_some() || self.has_quantity.is_some() || self.quantity.is_some() || self.unit.is_some() || self.unit_price.is_some() || self.is_reconciled.is_some() || self.reconciliation_id.is_some() || self.reconciled_at.is_some() || self.is_posted.is_some() || self.ledger_id.is_some() || self.posted_at.is_some() || self.tags.is_some() || self.data.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for JournalLine entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct JournalLineResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub journal_id: Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub outlet_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub line_number: i32,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub account_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub account_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub account_name: String,
    pub debit_amount: Decimal,
    pub credit_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub exchange_rate: Decimal,
    pub base_debit_amount: Decimal,
    pub base_credit_amount: Decimal,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost_center: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source_reference: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_tax_line: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_base_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub related_line_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub has_quantity: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit_price: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_reconciled: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reconciliation_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reconciled_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_posted: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ledger_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub posted_at: Option<DateTime<Utc>>,
    pub tags: serde_json::Value,
    pub data: serde_json::Value,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for JournalLine entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct JournalLineListResponseDto {
    /// List of items
    pub items: Vec<JournalLineResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl JournalLineListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<JournalLineResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct JournalLineSummaryDto {
    pub id: Uuid,
    pub journal_id: Uuid,
    pub provider_id: Option<Uuid>,
    pub outlet_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<JournalLine> for JournalLineResponseDto {
    fn from(entity: JournalLine) -> Self {
        Self {
            id: entity.id,
            journal_id: entity.journal_id,
            provider_id: entity.provider_id,
            outlet_id: entity.outlet_id,
            line_number: entity.line_number,
            account_id: entity.account_id,
            account_number: entity.account_number,
            account_name: entity.account_name,
            debit_amount: entity.debit_amount,
            credit_amount: entity.credit_amount,
            currency: entity.currency,
            exchange_rate: entity.exchange_rate,
            base_debit_amount: entity.base_debit_amount,
            base_credit_amount: entity.base_credit_amount,
            description: entity.description,
            cost_center: entity.cost_center,
            project: entity.project,
            department: entity.department,
            source_type: entity.source_type,
            source_id: entity.source_id,
            source_reference: entity.source_reference,
            is_tax_line: entity.is_tax_line,
            tax_rate: entity.tax_rate,
            tax_base_amount: entity.tax_base_amount,
            related_line_id: entity.related_line_id,
            has_quantity: entity.has_quantity,
            quantity: entity.quantity,
            unit: entity.unit,
            unit_price: entity.unit_price,
            is_reconciled: entity.is_reconciled,
            reconciliation_id: entity.reconciliation_id,
            reconciled_at: entity.reconciled_at,
            is_posted: entity.is_posted,
            ledger_id: entity.ledger_id,
            posted_at: entity.posted_at,
            tags: entity.tags,
            data: entity.data,
        }
    }
}

impl From<JournalLine> for JournalLineSummaryDto {
    fn from(entity: JournalLine) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            journal_id: entity.journal_id,
            provider_id: entity.provider_id,
            outlet_id: entity.outlet_id,
            created_at,
        }
    }
}

impl From<CreateJournalLineDto> for JournalLine {
    fn from(dto: CreateJournalLineDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            journal_id: dto.journal_id,
            provider_id: dto.provider_id,
            outlet_id: dto.outlet_id,
            line_number: dto.line_number,
            account_id: dto.account_id,
            account_number: dto.account_number,
            account_name: dto.account_name,
            debit_amount: dto.debit_amount,
            credit_amount: dto.credit_amount,
            currency: dto.currency,
            exchange_rate: dto.exchange_rate,
            base_debit_amount: dto.base_debit_amount,
            base_credit_amount: dto.base_credit_amount,
            description: dto.description,
            cost_center: dto.cost_center,
            project: dto.project,
            department: dto.department,
            source_type: dto.source_type,
            source_id: dto.source_id,
            source_reference: dto.source_reference,
            is_tax_line: dto.is_tax_line,
            tax_rate: dto.tax_rate,
            tax_base_amount: dto.tax_base_amount,
            related_line_id: dto.related_line_id,
            has_quantity: dto.has_quantity,
            quantity: dto.quantity,
            unit: dto.unit,
            unit_price: dto.unit_price,
            is_reconciled: dto.is_reconciled,
            reconciliation_id: dto.reconciliation_id,
            reconciled_at: dto.reconciled_at,
            is_posted: dto.is_posted,
            ledger_id: dto.ledger_id,
            posted_at: dto.posted_at,
            tags: dto.tags,
            data: dto.data,
        }
    }
}

impl From<&JournalLine> for JournalLineResponseDto {
    fn from(entity: &JournalLine) -> Self {
        Self {
            id: entity.id.clone(),
            journal_id: entity.journal_id.clone(),
            provider_id: entity.provider_id.clone(),
            outlet_id: entity.outlet_id.clone(),
            line_number: entity.line_number.clone(),
            account_id: entity.account_id.clone(),
            account_number: entity.account_number.clone(),
            account_name: entity.account_name.clone(),
            debit_amount: entity.debit_amount.clone(),
            credit_amount: entity.credit_amount.clone(),
            currency: entity.currency.clone(),
            exchange_rate: entity.exchange_rate.clone(),
            base_debit_amount: entity.base_debit_amount.clone(),
            base_credit_amount: entity.base_credit_amount.clone(),
            description: entity.description.clone(),
            cost_center: entity.cost_center.clone(),
            project: entity.project.clone(),
            department: entity.department.clone(),
            source_type: entity.source_type.clone(),
            source_id: entity.source_id.clone(),
            source_reference: entity.source_reference.clone(),
            is_tax_line: entity.is_tax_line.clone(),
            tax_rate: entity.tax_rate.clone(),
            tax_base_amount: entity.tax_base_amount.clone(),
            related_line_id: entity.related_line_id.clone(),
            has_quantity: entity.has_quantity.clone(),
            quantity: entity.quantity.clone(),
            unit: entity.unit.clone(),
            unit_price: entity.unit_price.clone(),
            is_reconciled: entity.is_reconciled.clone(),
            reconciliation_id: entity.reconciliation_id.clone(),
            reconciled_at: entity.reconciled_at.clone(),
            is_posted: entity.is_posted.clone(),
            ledger_id: entity.ledger_id.clone(),
            posted_at: entity.posted_at.clone(),
            tags: entity.tags.clone(),
            data: entity.data.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateJournalLineDto> for JournalLine {
    fn from_create_dto(dto: CreateJournalLineDto) -> backbone_core::ServiceResult<Self> {
        Ok(JournalLine::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateJournalLineDto> for JournalLine {
    fn apply_update(mut self, dto: UpdateJournalLineDto) -> backbone_core::ServiceResult<Self> {
        self.journal_id = dto.journal_id;
        self.provider_id = dto.provider_id;
        self.outlet_id = dto.outlet_id;
        self.line_number = dto.line_number;
        self.account_id = dto.account_id;
        self.account_number = dto.account_number;
        self.account_name = dto.account_name;
        self.debit_amount = dto.debit_amount;
        self.credit_amount = dto.credit_amount;
        self.currency = dto.currency;
        self.exchange_rate = dto.exchange_rate;
        self.base_debit_amount = dto.base_debit_amount;
        self.base_credit_amount = dto.base_credit_amount;
        self.description = dto.description;
        self.cost_center = dto.cost_center;
        self.project = dto.project;
        self.department = dto.department;
        self.source_type = dto.source_type;
        self.source_id = dto.source_id;
        self.source_reference = dto.source_reference;
        self.is_tax_line = dto.is_tax_line;
        self.tax_rate = dto.tax_rate;
        self.tax_base_amount = dto.tax_base_amount;
        self.related_line_id = dto.related_line_id;
        self.has_quantity = dto.has_quantity;
        self.quantity = dto.quantity;
        self.unit = dto.unit;
        self.unit_price = dto.unit_price;
        self.is_reconciled = dto.is_reconciled;
        self.reconciliation_id = dto.reconciliation_id;
        self.reconciled_at = dto.reconciled_at;
        self.is_posted = dto.is_posted;
        self.ledger_id = dto.ledger_id;
        self.posted_at = dto.posted_at;
        self.tags = dto.tags;
        self.data = dto.data;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to JournalLine here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

