//! Domain policy for Reconciliation aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Reconciliation;

/// Domain policy for Reconciliation — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Reconciliation>` in the `// <<< CUSTOM` zone.
pub type ReconciliationDomainPolicy = PermitAllPolicy<Reconciliation>;

// <<< CUSTOM
// END CUSTOM
