//! Application service for Account entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `account_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAccountDto, UpdateAccountDto};
use crate::domain::entity::Account;
use crate::infrastructure::persistence::AccountRepository;

/// Application service for Account entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `account_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AccountServiceCustom {
///     inner: Arc<AccountService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AccountService = GenericCrudService<
    Account,
    CreateAccountDto,
    UpdateAccountDto,
    AccountRepository,
>;

// <<< CUSTOM
// END CUSTOM
