//! Application service for FiscalPeriod entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `fiscal_period_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateFiscalPeriodDto, UpdateFiscalPeriodDto};
use crate::domain::entity::FiscalPeriod;
use crate::infrastructure::persistence::FiscalPeriodRepository;

/// Application service for FiscalPeriod entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `fiscal_period_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct FiscalPeriodServiceCustom {
///     inner: Arc<FiscalPeriodService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type FiscalPeriodService = GenericCrudService<
    FiscalPeriod,
    CreateFiscalPeriodDto,
    UpdateFiscalPeriodDto,
    FiscalPeriodRepository,
>;

// <<< CUSTOM
// END CUSTOM
