//! Application service for FullReconcile entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `full_reconcile_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateFullReconcileDto, UpdateFullReconcileDto};
use crate::domain::entity::FullReconcile;
use crate::infrastructure::persistence::FullReconcileRepository;

/// Application service for FullReconcile entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `full_reconcile_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct FullReconcileServiceCustom {
///     inner: Arc<FullReconcileService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type FullReconcileService = GenericCrudService<
    FullReconcile,
    CreateFullReconcileDto,
    UpdateFullReconcileDto,
    FullReconcileRepository,
>;

// <<< CUSTOM
// END CUSTOM
