//! Application service for Journal entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `journal_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateJournalDto, UpdateJournalDto};
use crate::domain::entity::Journal;
use crate::infrastructure::persistence::JournalRepository;

/// Application service for Journal entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `journal_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct JournalServiceCustom {
///     inner: Arc<JournalService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type JournalService = GenericCrudService<
    Journal,
    CreateJournalDto,
    UpdateJournalDto,
    JournalRepository,
>;

// <<< CUSTOM
// END CUSTOM
