//! Application service for JournalLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `journal_line_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateJournalLineDto, UpdateJournalLineDto};
use crate::domain::entity::JournalLine;
use crate::infrastructure::persistence::JournalLineRepository;

/// Application service for JournalLine entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `journal_line_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct JournalLineServiceCustom {
///     inner: Arc<JournalLineService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type JournalLineService = GenericCrudService<
    JournalLine,
    CreateJournalLineDto,
    UpdateJournalLineDto,
    JournalLineRepository,
>;

// <<< CUSTOM
// END CUSTOM
