//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod account_service;
pub mod accounting_post_service;
pub mod cost_center_service;
pub mod financial_statement_service;
pub mod fiscal_period_service;
pub mod journal_service;
pub mod journal_line_service;
pub mod ledger_service;
pub mod reconciliation_service;
pub mod reconciliation_item_service;

// <<< CUSTOM
pub mod posting_service;
pub mod reporting_service;
pub mod bank_reconciliation_service;
pub mod period_close_service;
pub mod journal_workflow_service;
// END CUSTOM

pub use account_service::AccountService;
pub use accounting_post_service::AccountingPostService;
pub use cost_center_service::CostCenterService;
pub use financial_statement_service::FinancialStatementService;
pub use fiscal_period_service::FiscalPeriodService;
pub use journal_service::JournalService;
pub use journal_line_service::JournalLineService;
pub use ledger_service::LedgerService;
pub use reconciliation_service::ReconciliationService;
pub use reconciliation_item_service::ReconciliationItemService;
// <<< CUSTOM
pub use posting_service::{
    AccountingPostFailed, AccountingPostPosted, LoggingSink, PostingError, PostingEvent,
    PostingEventSink, PostingLine, PostingRequest, PostingResult, PostingService,
};
pub use reporting_service::{
    BalanceSheet, IncomeStatement, ReportingService, TrialBalance, TrialBalanceLine,
};
pub use bank_reconciliation_service::{
    BankReconciliationService, ReconcileError, ReconcileRequest, ReconcileResult, StatementLine,
};
pub use period_close_service::{PeriodCloseError, PeriodCloseResult, PeriodCloseService};
pub use journal_workflow_service::{JournalWorkflowError, JournalWorkflowService};
pub mod hierarchy_service;
pub use hierarchy_service::HierarchyService;
// END CUSTOM