//! Application service for PrintedCheck entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `printed_check_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePrintedCheckDto, UpdatePrintedCheckDto};
use crate::domain::entity::PrintedCheck;
use crate::infrastructure::persistence::PrintedCheckRepository;

/// Application service for PrintedCheck entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `printed_check_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PrintedCheckServiceCustom {
///     inner: Arc<PrintedCheckService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PrintedCheckService = GenericCrudService<
    PrintedCheck,
    CreatePrintedCheckDto,
    UpdatePrintedCheckDto,
    PrintedCheckRepository,
>;

// <<< CUSTOM
// END CUSTOM
