-- SEED: none
--
-- The chart of accounts is not global reference data. An account belongs to a
-- company, which the tenancy descriptor enforces: accounts must anchor on a
-- company or branch node and are refused on the tenant root. A seed run has no
-- company to anchor to, so this table cannot be filled that way even in
-- principle.
--
-- The real path is the chart-install verb, which installs a named chart for the
-- acting company from the localization dataset. That dataset ships 218 accounts
-- against the roughly twenty this file used to carry, so nothing is lost by
-- retiring it — the verb was always the richer and the correct route.
--
-- To install: POST the chart-install verb with a chart code, per company.
