-- Account Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the accounting.accounts table.
-- Customize this file to add your initial data.

-- INSERT INTO accounting.accounts (
--     id,
--     company_id,
--     account_number,
--     account_code,
--     name,
--     description,
--     account_type,
--     account_subtype,
--     normal_balance,
--     parent_id,
--     level,
--     path,
--     is_header,
--     is_detail,
--     currency,
--     opening_balance,
--     opening_balance_date,
--     current_balance,
--     is_reconcilable,
--     has_budget,
--     budget_amount,
--     sort_order,
--     show_in_reports,
--     status,
--     is_system,
--     notes,
--     source_id,
--     is_cloned,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO accounting.accounts (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

INSERT INTO accounting.accounts
    (id, company_id, account_number, account_code, name, account_type, account_subtype,
     normal_balance, parent_id, level, path, is_header, is_detail, currency, is_reconcilable,
     show_in_reports, status)
VALUES
    -- ===== 1. ASET (Assets) =====
    ('11111111-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001',
     '1-0000', '1-0000', 'Aset', 'asset'::account_type, 'current_asset'::account_subtype,
     'debit'::normal_balance, NULL, 0, '1-0000', TRUE, FALSE, 'IDR', FALSE, TRUE, 'active'::account_status),

    ('11111111-0000-0000-0000-000000000010', '00000000-0000-0000-0000-000000000001',
     '1-1000', '1-1000', 'Kas', 'asset'::account_type, 'cash'::account_subtype,
     'debit'::normal_balance, '11111111-0000-0000-0000-000000000001', 1, '1-0000/1-1000',
     FALSE, TRUE, 'IDR', FALSE, TRUE, 'active'::account_status),

    ('11111111-0000-0000-0000-000000000020', '00000000-0000-0000-0000-000000000001',
     '1-1100', '1-1100', 'Bank', 'asset'::account_type, 'bank'::account_subtype,
     'debit'::normal_balance, '11111111-0000-0000-0000-000000000001', 1, '1-0000/1-1100',
     FALSE, TRUE, 'IDR', TRUE, TRUE, 'active'::account_status),

    ('11111111-0000-0000-0000-000000000030', '00000000-0000-0000-0000-000000000001',
     '1-2000', '1-2000', 'Piutang Usaha', 'asset'::account_type,
     'accounts_receivable'::account_subtype, 'debit'::normal_balance,
     '11111111-0000-0000-0000-000000000001', 1, '1-0000/1-2000', FALSE, TRUE, 'IDR',
     FALSE, TRUE, 'active'::account_status),

    ('11111111-0000-0000-0000-000000000040', '00000000-0000-0000-0000-000000000001',
     '1-3000', '1-3000', 'Persediaan', 'asset'::account_type,
     'inventory'::account_subtype, 'debit'::normal_balance,
     '11111111-0000-0000-0000-000000000001', 1, '1-0000/1-3000', FALSE, TRUE, 'IDR',
     FALSE, TRUE, 'active'::account_status),

    -- PPN Masukan (input VAT) — a tax receivable, debit-normal, lives under assets.
    ('11111111-0000-0000-0000-000000000050', '00000000-0000-0000-0000-000000000001',
     '1-4000', '1-4000', 'PPN Masukan', 'asset'::account_type,
     'tax'::account_subtype, 'debit'::normal_balance,
     '11111111-0000-0000-0000-000000000001', 1, '1-0000/1-4000', FALSE, TRUE, 'IDR',
     FALSE, TRUE, 'active'::account_status),

    -- ===== 2. LIABILITAS (Liabilities) =====
    ('22222222-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001',
     '2-0000', '2-0000', 'Liabilitas', 'liability'::account_type,
     'current_liability'::account_subtype, 'credit'::normal_balance, NULL, 0, '2-0000',
     TRUE, FALSE, 'IDR', FALSE, TRUE, 'active'::account_status),

    ('22222222-0000-0000-0000-000000000010', '00000000-0000-0000-0000-000000000001',
     '2-1000', '2-1000', 'Hutang Usaha', 'liability'::account_type,
     'accounts_payable'::account_subtype, 'credit'::normal_balance,
     '22222222-0000-0000-0000-000000000001', 1, '2-0000/2-1000', FALSE, TRUE, 'IDR',
     FALSE, TRUE, 'active'::account_status),

    -- PPN Keluaran (output VAT payable) — credit-normal liability. G1 credits this account.
    ('22222222-0000-0000-0000-000000000020', '00000000-0000-0000-0000-000000000001',
     '2-2000', '2-2000', 'PPN Keluaran', 'liability'::account_type,
     'tax'::account_subtype, 'credit'::normal_balance,
     '22222222-0000-0000-0000-000000000001', 1, '2-0000/2-2000', FALSE, TRUE, 'IDR',
     FALSE, TRUE, 'active'::account_status),

    -- PPh Payable (income-tax withholding payable).
    ('22222222-0000-0000-0000-000000000030', '00000000-0000-0000-0000-000000000001',
     '2-3000', '2-3000', 'Hutang PPh', 'liability'::account_type,
     'tax'::account_subtype, 'credit'::normal_balance,
     '22222222-0000-0000-0000-000000000001', 1, '2-0000/2-3000', FALSE, TRUE, 'IDR',
     FALSE, TRUE, 'active'::account_status),

    -- ===== 3. EKUITAS (Equity) =====
    ('33333333-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001',
     '3-0000', '3-0000', 'Ekuitas', 'equity'::account_type,
     'paid_in_capital'::account_subtype, 'credit'::normal_balance, NULL, 0, '3-0000',
     TRUE, FALSE, 'IDR', FALSE, TRUE, 'active'::account_status),

    -- Retained Earnings — period close zeroes revenue/expense into this account.
    ('33333333-0000-0000-0000-000000000010', '00000000-0000-0000-0000-000000000001',
     '3-1000', '3-1000', 'Laba Ditahan', 'equity'::account_type,
     'retained_earnings'::account_subtype, 'credit'::normal_balance,
     '33333333-0000-0000-0000-000000000001', 1, '3-0000/3-1000', FALSE, TRUE, 'IDR',
     FALSE, TRUE, 'active'::account_status),

    -- ===== 4. PENDAPATAN (Revenue) =====
    ('44444444-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001',
     '4-0000', '4-0000', 'Pendapatan', 'revenue'::account_type,
     'operating_revenue'::account_subtype, 'credit'::normal_balance, NULL, 0, '4-0000',
     TRUE, FALSE, 'IDR', FALSE, TRUE, 'active'::account_status),

    ('44444444-0000-0000-0000-000000000010', '00000000-0000-0000-0000-000000000001',
     '4-1000', '4-1000', 'Pendapatan Penjualan', 'revenue'::account_type,
     'operating_revenue'::account_subtype, 'credit'::normal_balance,
     '44444444-0000-0000-0000-000000000001', 1, '4-0000/4-1000', FALSE, TRUE, 'IDR',
     FALSE, TRUE, 'active'::account_status),

    -- ===== 5. HPP (Cost of Goods Sold) =====
    ('55555555-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001',
     '5-0000', '5-0000', 'Harga Pokok Penjualan', 'cogs'::account_type,
     'direct_cost'::account_subtype, 'debit'::normal_balance, NULL, 0, '5-0000',
     TRUE, FALSE, 'IDR', FALSE, TRUE, 'active'::account_status),

    ('55555555-0000-0000-0000-000000000010', '00000000-0000-0000-0000-000000000001',
     '5-1000', '5-1000', 'HPP', 'cogs'::account_type,
     'direct_cost'::account_subtype, 'debit'::normal_balance,
     '55555555-0000-0000-0000-000000000001', 1, '5-0000/5-1000', FALSE, TRUE, 'IDR',
     FALSE, TRUE, 'active'::account_status),

    -- ===== 6. BEBAN (Expenses) =====
    ('66666666-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000001',
     '6-0000', '6-0000', 'Beban Operasional', 'expense'::account_type,
     'operating_expense'::account_subtype, 'debit'::normal_balance, NULL, 0, '6-0000',
     TRUE, FALSE, 'IDR', FALSE, TRUE, 'active'::account_status),

    -- Bank Charges — G8 reconciliation adjusting entry debits this account.
    ('66666666-0000-0000-0000-000000000010', '00000000-0000-0000-0000-000000000001',
     '6-1000', '6-1000', 'Beban Admin Bank', 'expense'::account_type,
     'operating_expense'::account_subtype, 'debit'::normal_balance,
     '66666666-0000-0000-0000-000000000001', 1, '6-0000/6-1000', FALSE, TRUE, 'IDR',
     FALSE, TRUE, 'active'::account_status)
ON CONFLICT DO NOTHING;