-- Migration: Create accounts table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS accounts (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    provider_id UUID,
    account_number TEXT NOT NULL,
    account_code TEXT NOT NULL,
    name TEXT NOT NULL,
    name_en TEXT,
    description TEXT,
    account_type account_type NOT NULL,
    account_subtype account_subtype NOT NULL,
    normal_balance normal_balance NOT NULL,
    parent_id UUID,
    level INTEGER NOT NULL DEFAULT 0,
    path TEXT,
    is_header BOOLEAN NOT NULL DEFAULT FALSE,
    is_detail BOOLEAN NOT NULL DEFAULT TRUE,
    currency TEXT NOT NULL DEFAULT 'IDR',
    opening_balance NUMERIC NOT NULL DEFAULT 0,
    opening_balance_date DATE,
    current_balance NUMERIC NOT NULL DEFAULT 0,
    bank_name TEXT,
    bank_account_number TEXT,
    bank_account_name TEXT,
    bank_branch TEXT,
    is_taxable BOOLEAN NOT NULL DEFAULT FALSE,
    tax_rate NUMERIC,
    tax_account_id UUID,
    is_reconcilable BOOLEAN NOT NULL DEFAULT FALSE,
    last_reconciled_at TIMESTAMPTZ,
    last_reconciled_balance NUMERIC,
    has_budget BOOLEAN NOT NULL DEFAULT FALSE,
    budget_amount NUMERIC,
    allow_manual_entry BOOLEAN NOT NULL DEFAULT TRUE,
    require_cost_center BOOLEAN NOT NULL DEFAULT FALSE,
    require_project BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    show_in_reports BOOLEAN NOT NULL DEFAULT TRUE,
    status account_status NOT NULL DEFAULT 'active',
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    source_id UUID,
    is_cloned BOOLEAN NOT NULL DEFAULT FALSE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_accounts_provider_id_account_number ON accounts (provider_id, account_number) WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_accounts_provider_id_account_code ON accounts (provider_id, account_code) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_accounts_provider_id_account_type_status ON accounts (provider_id, account_type, status);

CREATE INDEX IF NOT EXISTS idx_accounts_provider_id_parent_id_sort_order ON accounts (provider_id, parent_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_accounts_provider_id_account_subtype ON accounts (provider_id, account_subtype);

CREATE INDEX IF NOT EXISTS idx_accounts_provider_id_is_reconcilable ON accounts (provider_id, is_reconcilable);

CREATE INDEX IF NOT EXISTS idx_accounts_source_id_is_cloned ON accounts (source_id, is_cloned);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_accounts_metadata_gin ON accounts USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_accounts_metadata_deleted_at ON accounts ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION accounts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS accounts_insert_audit ON accounts;
CREATE TRIGGER accounts_insert_audit BEFORE INSERT ON accounts
    FOR EACH ROW EXECUTE FUNCTION accounts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS accounts_update_audit ON accounts;
CREATE TRIGGER accounts_update_audit BEFORE UPDATE ON accounts
    FOR EACH ROW EXECUTE FUNCTION accounts_audit_timestamp();

