-- Migration: Create reconciliations table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS reconciliations (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    provider_id UUID,
    reconciliation_number TEXT NOT NULL,
    account_id UUID NOT NULL,
    account_number TEXT NOT NULL,
    account_name TEXT NOT NULL,
    reconciliation_type reconciliation_type NOT NULL DEFAULT 'bank',
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    statement_date DATE NOT NULL,
    opening_book_balance NUMERIC NOT NULL,
    opening_statement_balance NUMERIC NOT NULL,
    previous_reconciliation_id UUID,
    closing_book_balance NUMERIC NOT NULL,
    closing_statement_balance NUMERIC NOT NULL,
    total_matched_debits NUMERIC NOT NULL DEFAULT 0,
    total_matched_credits NUMERIC NOT NULL DEFAULT 0,
    matched_count INTEGER NOT NULL DEFAULT 0,
    total_unmatched_book_debits NUMERIC NOT NULL DEFAULT 0,
    total_unmatched_book_credits NUMERIC NOT NULL DEFAULT 0,
    unmatched_book_count INTEGER NOT NULL DEFAULT 0,
    total_unmatched_statement_debits NUMERIC NOT NULL DEFAULT 0,
    total_unmatched_statement_credits NUMERIC NOT NULL DEFAULT 0,
    unmatched_statement_count INTEGER NOT NULL DEFAULT 0,
    outstanding_deposits NUMERIC NOT NULL DEFAULT 0,
    outstanding_checks NUMERIC NOT NULL DEFAULT 0,
    deposits_in_transit NUMERIC NOT NULL DEFAULT 0,
    bank_charges NUMERIC NOT NULL DEFAULT 0,
    bank_interest NUMERIC NOT NULL DEFAULT 0,
    nsf_checks NUMERIC NOT NULL DEFAULT 0,
    other_adjustments NUMERIC NOT NULL DEFAULT 0,
    adjusted_book_balance NUMERIC,
    adjusted_statement_balance NUMERIC,
    difference NUMERIC NOT NULL DEFAULT 0,
    is_balanced BOOLEAN NOT NULL DEFAULT FALSE,
    status reconciliation_status NOT NULL DEFAULT 'in_progress',
    started_at TIMESTAMPTZ,
    started_by UUID,
    completed_at TIMESTAMPTZ,
    completed_by UUID,
    reviewed_at TIMESTAMPTZ,
    reviewed_by UUID,
    has_adjusting_entries BOOLEAN NOT NULL DEFAULT FALSE,
    adjusting_journal_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    statement_source TEXT,
    statement_file_url TEXT,
    import_date TIMESTAMPTZ,
    notes TEXT,
    discrepancy_notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_reconciliations_provider_id_reconciliation_number ON reconciliations (provider_id, reconciliation_number) WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_reconciliations_provider_id_account_id_statement_date ON reconciliations (provider_id, account_id, statement_date) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_reconciliations_provider_id_account_id_period_start ON reconciliations (provider_id, account_id, period_start);

CREATE INDEX IF NOT EXISTS idx_reconciliations_provider_id_status ON reconciliations (provider_id, status);

CREATE INDEX IF NOT EXISTS idx_reconciliations_provider_id_is_balanced ON reconciliations (provider_id, is_balanced);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_reconciliations_metadata_gin ON reconciliations USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_reconciliations_metadata_deleted_at ON reconciliations ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION reconciliations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS reconciliations_insert_audit ON reconciliations;
CREATE TRIGGER reconciliations_insert_audit BEFORE INSERT ON reconciliations
    FOR EACH ROW EXECUTE FUNCTION reconciliations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS reconciliations_update_audit ON reconciliations;
CREATE TRIGGER reconciliations_update_audit BEFORE UPDATE ON reconciliations
    FOR EACH ROW EXECUTE FUNCTION reconciliations_audit_timestamp();

