-- Migration: Create full_reconciles table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS accounting;

CREATE TABLE IF NOT EXISTS accounting.full_reconciles (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    exchange_total NUMERIC(18, 2) NOT NULL DEFAULT 0,
    reconciled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_full_reconciles_company_id_reconciled_at ON accounting.full_reconciles (company_id, reconciled_at);

-- Company fence (ADR-0014: strict) — same posture as every company-scoped table in this
-- module: a session sees only rows whose company_id equals the request-scoped company
-- (`set_config('app.company_id', <uuid>, true)`); an unset var sees zero rows (fail-closed).
-- Requires the app to connect as a non-superuser role; migrations/seeders run as the
-- owner and bypass.
ALTER TABLE accounting.full_reconciles ENABLE ROW LEVEL SECURITY;
ALTER TABLE accounting.full_reconciles FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS full_reconciles_company_isolation ON accounting.full_reconciles;
CREATE POLICY full_reconciles_company_isolation ON accounting.full_reconciles
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);
