-- Migration: Create journals table
-- Generated by metaphor-schema

-- Create journal_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'journal_type') THEN
        CREATE TYPE journal_type AS ENUM ('general', 'sales', 'purchase', 'cash_receipt', 'cash_disbursement', 'payroll', 'adjusting', 'closing', 'reversing', 'opening');
    END IF;
END
$$;

-- Create journal_source enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'journal_source') THEN
        CREATE TYPE journal_source AS ENUM ('manual', 'order', 'payment', 'settlement', 'adjustment', 'import', 'system', 'recurring');
    END IF;
END
$$;

-- Create journal_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'journal_status') THEN
        CREATE TYPE journal_status AS ENUM ('draft', 'pending_approval', 'approved', 'rejected', 'posted', 'voided');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS accounting;

CREATE TABLE IF NOT EXISTS accounting.journals (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    journal_number TEXT NOT NULL,
    reference_number TEXT,
    journal_type journal_type NOT NULL DEFAULT 'general',
    branch_id UUID,
    transaction_date DATE NOT NULL,
    posting_date DATE,
    fiscal_period_id UUID,
    fiscal_year INTEGER,
    fiscal_month INTEGER,
    description TEXT NOT NULL,
    notes TEXT,
    currency TEXT NOT NULL DEFAULT 'IDR',
    total_debit NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (total_debit >= 0),
    total_credit NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (total_credit >= 0),
    line_count INTEGER NOT NULL DEFAULT 0 CHECK (line_count >= 0),
    source journal_source NOT NULL DEFAULT 'manual',
    source_type TEXT,
    source_id UUID,
    source_reference TEXT,
    is_reversed BOOLEAN NOT NULL DEFAULT FALSE,
    reversed_by_id UUID,
    reversed_at TIMESTAMPTZ,
    reversal_reason TEXT,
    reverses_id UUID,
    is_reversing BOOLEAN NOT NULL DEFAULT FALSE,
    auto_reverse BOOLEAN NOT NULL DEFAULT FALSE,
    auto_reverse_date DATE,
    status journal_status NOT NULL DEFAULT 'draft',
    requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
    approval_threshold NUMERIC(18, 2),
    submitted_at TIMESTAMPTZ,
    submitted_by UUID,
    approved_at TIMESTAMPTZ,
    approved_by UUID,
    rejected_at TIMESTAMPTZ,
    rejected_by UUID,
    rejection_reason TEXT,
    posted_at TIMESTAMPTZ,
    posted_by UUID,
    is_voided BOOLEAN NOT NULL DEFAULT FALSE,
    voided_at TIMESTAMPTZ,
    voided_by UUID,
    void_reason TEXT,
    attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_journals_company_id_journal_number ON accounting.journals (company_id, journal_number) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_journals_company_id_transaction_date ON accounting.journals (company_id, transaction_date);

CREATE INDEX IF NOT EXISTS idx_journals_company_id_journal_type_status ON accounting.journals (company_id, journal_type, status);

CREATE INDEX IF NOT EXISTS idx_journals_company_id_fiscal_year_fiscal_month ON accounting.journals (company_id, fiscal_year, fiscal_month);

CREATE INDEX IF NOT EXISTS idx_journals_company_id_status_transaction_date ON accounting.journals (company_id, status, transaction_date);

CREATE INDEX IF NOT EXISTS idx_journals_source_source_id ON accounting.journals (source, source_id);

CREATE INDEX IF NOT EXISTS idx_journals_company_id_is_reversed ON accounting.journals (company_id, is_reversed);

CREATE INDEX IF NOT EXISTS idx_journals_company_id_branch_id_transaction_date ON accounting.journals (company_id, branch_id, transaction_date);

CREATE INDEX IF NOT EXISTS idx_journals_branch_id_status ON accounting.journals (branch_id, status) WHERE branch_id IS NOT NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_journals_metadata_gin ON accounting.journals USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_journals_metadata_deleted_at ON accounting.journals ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_journals_metadata_created_at ON accounting.journals ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_journals_metadata_updated_at ON accounting.journals ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION accounting.journals_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS journals_insert_audit ON accounting.journals;
CREATE TRIGGER journals_insert_audit BEFORE INSERT ON accounting.journals
    FOR EACH ROW EXECUTE FUNCTION accounting.journals_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS journals_update_audit ON accounting.journals;
CREATE TRIGGER journals_update_audit BEFORE UPDATE ON accounting.journals
    FOR EACH ROW EXECUTE FUNCTION accounting.journals_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE accounting.journals ADD CONSTRAINT fk_journals_fiscal_period_id FOREIGN KEY (fiscal_period_id) REFERENCES accounting.fiscal_periods (id);
ALTER TABLE accounting.journals ADD CONSTRAINT fk_journals_reversed_by_id FOREIGN KEY (reversed_by_id) REFERENCES accounting.journals (id);
ALTER TABLE accounting.journals ADD CONSTRAINT fk_journals_reverses_id FOREIGN KEY (reverses_id) REFERENCES accounting.journals (id);
