-- Enum types for accounting module
-- Generated by metaphor-schema

-- Create account_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'account_type') THEN
        CREATE TYPE account_type AS ENUM ('asset', 'liability', 'equity', 'revenue', 'expense', 'cogs', 'other_income', 'other_expense');
    END IF;
END
$$;

-- Create account_subtype enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'account_subtype') THEN
        CREATE TYPE account_subtype AS ENUM ('current_asset', 'non_current_asset', 'fixed_asset', 'accumulated_depreciation', 'current_liability', 'non_current_liability', 'paid_in_capital', 'retained_earnings', 'operating_revenue', 'operating_expense', 'direct_cost', 'bank', 'cash', 'accounts_receivable', 'accounts_payable', 'tax', 'inventory');
    END IF;
END
$$;

-- Create normal_balance enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'normal_balance') THEN
        CREATE TYPE normal_balance AS ENUM ('debit', 'credit');
    END IF;
END
$$;

-- Create account_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'account_status') THEN
        CREATE TYPE account_status AS ENUM ('active', 'inactive', 'archived');
    END IF;
END
$$;

-- Create party_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'party_type') THEN
        CREATE TYPE party_type AS ENUM ('customer', 'supplier', 'employee');
    END IF;
END
$$;

-- Create posting_source_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'posting_source_type') THEN
        CREATE TYPE posting_source_type AS ENUM ('order', 'payment', 'settlement', 'refund', 'expense', 'inventory', 'manufacturing', 'asset', 'payroll', 'maintenance', 'equity', 'manual');
    END IF;
END
$$;

-- Create posting_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'posting_type') THEN
        CREATE TYPE posting_type AS ENUM ('original', 'reversal', 'adjustment', 'correction');
    END IF;
END
$$;

-- Create posting_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'posting_status') THEN
        CREATE TYPE posting_status AS ENUM ('pending', 'processing', 'posted', 'failed', 'cancelled');
    END IF;
END
$$;

-- Create statement_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'statement_type') THEN
        CREATE TYPE statement_type AS ENUM ('balance_sheet', 'income_statement', 'cash_flow', 'trial_balance', 'equity_statement');
    END IF;
END
$$;

-- Create statement_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'statement_status') THEN
        CREATE TYPE statement_status AS ENUM ('draft', 'generated', 'reviewed', 'approved', 'published', 'archived');
    END IF;
END
$$;

-- Create period_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'period_type') THEN
        CREATE TYPE period_type AS ENUM ('monthly', 'quarterly', 'yearly', 'custom');
    END IF;
END
$$;

-- Create period_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'period_status') THEN
        CREATE TYPE period_status AS ENUM ('open', 'closing', 'closed', 'locked', 'adjusting');
    END IF;
END
$$;

-- Create journal_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'journal_type') THEN
        CREATE TYPE journal_type AS ENUM ('general', 'sales', 'purchase', 'cash_receipt', 'cash_disbursement', 'payroll', 'adjusting', 'closing', 'reversing', 'opening');
    END IF;
END
$$;

-- Create journal_source enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'journal_source') THEN
        CREATE TYPE journal_source AS ENUM ('manual', 'order', 'payment', 'settlement', 'adjustment', 'import', 'system', 'recurring');
    END IF;
END
$$;

-- Create journal_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'journal_status') THEN
        CREATE TYPE journal_status AS ENUM ('draft', 'pending_approval', 'approved', 'rejected', 'posted', 'voided');
    END IF;
END
$$;

-- Create reconciliation_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reconciliation_type') THEN
        CREATE TYPE reconciliation_type AS ENUM ('bank', 'accounts_receivable', 'accounts_payable', 'intercompany', 'other');
    END IF;
END
$$;

-- Create reconciliation_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reconciliation_status') THEN
        CREATE TYPE reconciliation_status AS ENUM ('in_progress', 'pending_review', 'reviewed', 'completed', 'cancelled');
    END IF;
END
$$;

-- Create reconciliation_item_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reconciliation_item_status') THEN
        CREATE TYPE reconciliation_item_status AS ENUM ('unmatched', 'matched', 'partial_match', 'adjusted', 'written_off', 'outstanding');
    END IF;
END
$$;

