-- Migration: Create journal_lines table
-- Generated by metaphor-schema

-- Create party_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'party_type') THEN
        CREATE TYPE party_type AS ENUM ('customer', 'supplier', 'employee');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS journal_lines (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    journal_id UUID NOT NULL,
    company_id UUID NOT NULL,
    branch_id UUID,
    party_type party_type,
    party_id UUID,
    line_number INTEGER NOT NULL,
    account_id UUID NOT NULL,
    account_number TEXT NOT NULL,
    account_name TEXT NOT NULL,
    debit_amount NUMERIC NOT NULL DEFAULT 0,
    credit_amount NUMERIC NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'IDR',
    exchange_rate NUMERIC NOT NULL DEFAULT 1,
    base_debit_amount NUMERIC NOT NULL DEFAULT 0,
    base_credit_amount NUMERIC NOT NULL DEFAULT 0,
    description TEXT,
    cost_center_id UUID,
    project_id UUID,
    department_id UUID,
    dimensions JSONB,
    source_type TEXT,
    source_id UUID,
    source_reference TEXT,
    is_tax_line BOOLEAN NOT NULL DEFAULT FALSE,
    tax_rate NUMERIC,
    tax_base_amount NUMERIC,
    related_line_id UUID,
    has_quantity BOOLEAN NOT NULL DEFAULT FALSE,
    quantity NUMERIC,
    unit TEXT,
    unit_price NUMERIC,
    is_reconciled BOOLEAN NOT NULL DEFAULT FALSE,
    reconciliation_id UUID,
    reconciled_at TIMESTAMPTZ,
    is_posted BOOLEAN NOT NULL DEFAULT FALSE,
    ledger_id UUID,
    posted_at TIMESTAMPTZ,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_journal_lines_journal_id_line_number ON journal_lines (journal_id, line_number);

CREATE INDEX IF NOT EXISTS idx_journal_lines_company_id_account_id ON journal_lines (company_id, account_id);

CREATE INDEX IF NOT EXISTS idx_journal_lines_journal_id_account_id ON journal_lines (journal_id, account_id);

CREATE INDEX IF NOT EXISTS idx_journal_lines_account_id_is_posted ON journal_lines (account_id, is_posted);

CREATE INDEX IF NOT EXISTS idx_journal_lines_company_id_is_reconciled ON journal_lines (company_id, is_reconciled);

CREATE INDEX IF NOT EXISTS idx_journal_lines_source_type_source_id ON journal_lines (source_type, source_id);

CREATE INDEX IF NOT EXISTS idx_journal_lines_cost_center_id ON journal_lines (cost_center_id) WHERE cost_center_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_journal_lines_project_id ON journal_lines (project_id) WHERE project_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_journal_lines_company_id_party_type_party_id_account_id ON journal_lines (company_id, party_type, party_id, account_id) WHERE party_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_journal_lines_branch_id_account_id ON journal_lines (branch_id, account_id) WHERE branch_id IS NOT NULL;

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE journal_lines ADD CONSTRAINT fk_journal_lines_journal_id FOREIGN KEY (journal_id) REFERENCES journals (id);
ALTER TABLE journal_lines ADD CONSTRAINT fk_journal_lines_account_id FOREIGN KEY (account_id) REFERENCES accounts (id);
ALTER TABLE journal_lines ADD CONSTRAINT fk_journal_lines_related_line_id FOREIGN KEY (related_line_id) REFERENCES journal_lines (id);
ALTER TABLE journal_lines ADD CONSTRAINT fk_journal_lines_reconciliation_id FOREIGN KEY (reconciliation_id) REFERENCES reconciliations (id);
ALTER TABLE journal_lines ADD CONSTRAINT fk_journal_lines_ledger_id FOREIGN KEY (ledger_id) REFERENCES ledgers (id);
ALTER TABLE journal_lines ADD CONSTRAINT fk_journal_lines_cost_center_id FOREIGN KEY (cost_center_id) REFERENCES cost_centers (id);
