-- Migration: Create cost_centers table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS accounting;

CREATE TABLE IF NOT EXISTS accounting.cost_centers (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    name_en TEXT,
    description TEXT,
    parent_id UUID,
    level INTEGER NOT NULL DEFAULT 0 CHECK (level >= 0),
    is_group BOOLEAN NOT NULL DEFAULT FALSE,
    branch_id UUID,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_cost_centers_company_id_code ON accounting.cost_centers (company_id, code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_cost_centers_company_id_parent_id_sort_order ON accounting.cost_centers (company_id, parent_id, sort_order);

CREATE INDEX IF NOT EXISTS idx_cost_centers_company_id_is_active ON accounting.cost_centers (company_id, is_active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_cost_centers_metadata_gin ON accounting.cost_centers USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_cost_centers_metadata_deleted_at ON accounting.cost_centers ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_cost_centers_metadata_created_at ON accounting.cost_centers ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_cost_centers_metadata_updated_at ON accounting.cost_centers ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION accounting.cost_centers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS cost_centers_insert_audit ON accounting.cost_centers;
CREATE TRIGGER cost_centers_insert_audit BEFORE INSERT ON accounting.cost_centers
    FOR EACH ROW EXECUTE FUNCTION accounting.cost_centers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS cost_centers_update_audit ON accounting.cost_centers;
CREATE TRIGGER cost_centers_update_audit BEFORE UPDATE ON accounting.cost_centers
    FOR EACH ROW EXECUTE FUNCTION accounting.cost_centers_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE accounting.cost_centers ADD CONSTRAINT fk_cost_centers_parent_id FOREIGN KEY (parent_id) REFERENCES accounting.cost_centers (id);
