-- Migration: Create printed_checks table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS accounting;

CREATE TABLE IF NOT EXISTS accounting.printed_checks (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    bank_account_id UUID NOT NULL,
    payment_id UUID NOT NULL,
    payment_number TEXT,
    check_number TEXT NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    payee_name TEXT,
    status TEXT NOT NULL DEFAULT 'printed',
    printed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    printed_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (id)
);
