//! Event handler trait for AccountingPost events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AccountingPostEvent;

/// Event handler for AccountingPost events.
/// Implement this trait to react to AccountingPost lifecycle events.
pub trait AccountingPostEventHandler: EventHandler<AccountingPostEvent> {}
