//! Event handler trait for AccountingPost events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::AccountingPostEvent;
use backbone_messaging::EventHandler;

/// Event handler for AccountingPost events.
/// Implement this trait to react to AccountingPost lifecycle events.
pub trait AccountingPostEventHandler: EventHandler<AccountingPostEvent> {}
