//! Domain events for CostCenter entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::CostCenter;

/// Domain events for CostCenter — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<CostCenter>)` variant.
pub type CostCenterEvent = CrudEvent<CostCenter>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for CostCenter events.
pub type CostCenterEventPublisher = Arc<dyn CrudEventPublisher<CostCenter> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCostCenterEventPublisher = NoOpCrudEventPublisher<CostCenter>;
