//! Domain events for FiscalPeriod entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::FiscalPeriod;

/// Domain events for FiscalPeriod — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<FiscalPeriod>)` variant.
pub type FiscalPeriodEvent = CrudEvent<FiscalPeriod>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for FiscalPeriod events.
pub type FiscalPeriodEventPublisher = Arc<dyn CrudEventPublisher<FiscalPeriod> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopFiscalPeriodEventPublisher = NoOpCrudEventPublisher<FiscalPeriod>;
