//! Domain events for FullReconcile entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::FullReconcile;
use backbone_messaging::CrudEvent;

/// Domain events for FullReconcile — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<FullReconcile>)` variant.
pub type FullReconcileEvent = CrudEvent<FullReconcile>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for FullReconcile events.
pub type FullReconcileEventPublisher = Arc<dyn CrudEventPublisher<FullReconcile> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopFullReconcileEventPublisher = NoOpCrudEventPublisher<FullReconcile>;
