//! Event handler trait for Journal events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::JournalEvent;

/// Event handler for Journal events.
/// Implement this trait to react to Journal lifecycle events.
pub trait JournalEventHandler: EventHandler<JournalEvent> {}
