//! Event handler trait for JournalLine events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::JournalLineEvent;
use backbone_messaging::EventHandler;

/// Event handler for JournalLine events.
/// Implement this trait to react to JournalLine lifecycle events.
pub trait JournalLineEventHandler: EventHandler<JournalLineEvent> {}
