//! Domain events for Journal entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Journal;

/// Domain events for Journal — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Journal>)` variant.
pub type JournalEvent = CrudEvent<Journal>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Journal events.
pub type JournalEventPublisher = Arc<dyn CrudEventPublisher<Journal> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopJournalEventPublisher = NoOpCrudEventPublisher<Journal>;
