//! Domain events for Ledger entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Ledger;

/// Domain events for Ledger — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Ledger>)` variant.
pub type LedgerEvent = CrudEvent<Ledger>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Ledger events.
pub type LedgerEventPublisher = Arc<dyn CrudEventPublisher<Ledger> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopLedgerEventPublisher = NoOpCrudEventPublisher<Ledger>;
