//! Event handler trait for PartialReconcile events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::PartialReconcileEvent;
use backbone_messaging::EventHandler;

/// Event handler for PartialReconcile events.
/// Implement this trait to react to PartialReconcile lifecycle events.
pub trait PartialReconcileEventHandler: EventHandler<PartialReconcileEvent> {}
