//! Event handler trait for PrintedCheck events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PrintedCheckEvent;

/// Event handler for PrintedCheck events.
/// Implement this trait to react to PrintedCheck lifecycle events.
pub trait PrintedCheckEventHandler: EventHandler<PrintedCheckEvent> {}
