//! Domain events for ReconciliationItem entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ReconciliationItem;

/// Domain events for ReconciliationItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ReconciliationItem>)` variant.
pub type ReconciliationItemEvent = CrudEvent<ReconciliationItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ReconciliationItem events.
pub type ReconciliationItemEventPublisher = Arc<dyn CrudEventPublisher<ReconciliationItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopReconciliationItemEventPublisher = NoOpCrudEventPublisher<ReconciliationItem>;
