//! Event handler trait for Reconciliation events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ReconciliationEvent;

/// Event handler for Reconciliation events.
/// Implement this trait to react to Reconciliation lifecycle events.
pub trait ReconciliationEventHandler: EventHandler<ReconciliationEvent> {}
