//! CostCenter seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial CostCenter data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// COSTCENTER SEEDER
// ============================================================================

/// Seeder for cost_center
pub struct SeedCostCenterSeeder;

impl SeedCostCenterSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCostCenterSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCostCenterSeeder {
    fn name(&self) -> &'static str {
        "SeedCostCenterSeeder"
    }

    fn order(&self) -> i32 {
        9
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if cost_centers table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM cost_centers")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/cost_center_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM cost_centers")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

