//! ReconciliationItem seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ReconciliationItem data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// RECONCILIATIONITEM SEEDER
// ============================================================================

/// Seeder for reconciliation_item
pub struct SeedReconciliationItemSeeder;

impl SeedReconciliationItemSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedReconciliationItemSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedReconciliationItemSeeder {
    fn name(&self) -> &'static str {
        "SeedReconciliationItemSeeder"
    }

    fn order(&self) -> i32 {
        7
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if accounting.reconciliation_items table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM accounting.reconciliation_items")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/reconciliation_item_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM accounting.reconciliation_items")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

