//! Repository trait for EmvQrConfig aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EmvQrConfig aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::EmvQrConfig;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmvQrConfigPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EmvQrConfigPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EmvQrConfigPaginatedResult {
    pub data: Vec<EmvQrConfig>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EmvQrConfigFilter {
    pub merchant_name: Option<String>,
    pub merchant_city: Option<String>,
    pub country_code: Option<String>,
    pub mcc: Option<String>,
    pub gui: Option<String>,
    pub merchant_identifier: Option<String>,
    pub currency: Option<String>,
    pub initiation_method: Option<String>,
    pub bank_account_id: Option<Uuid>,
}

impl EmvQrConfigFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.merchant_name.is_some() || self.merchant_city.is_some() || self.country_code.is_some() || self.mcc.is_some() || self.gui.is_some() || self.merchant_identifier.is_some() || self.currency.is_some() || self.initiation_method.is_some() || self.bank_account_id.is_some()
    }
}

/// Repository trait for EmvQrConfig aggregate
///
/// This trait defines the persistence contract for EmvQrConfig entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EmvQrConfigRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new emv_qr_config entity
    async fn save(&self, entity: &EmvQrConfig) -> Result<EmvQrConfig>;

    /// Find emv_qr_config by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EmvQrConfig>>;

    /// Find all emv_qr_config entities
    async fn find_all(&self) -> Result<Vec<EmvQrConfig>>;

    /// Update emv_qr_config by ID
    async fn update(&self, id: &str, entity: &EmvQrConfig) -> Result<Option<EmvQrConfig>>;

    /// Delete emv_qr_config by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List emv_qr_config with pagination
    async fn list(&self, params: EmvQrConfigPaginationParams) -> Result<EmvQrConfigPaginatedResult>;

    /// List emv_qr_config with pagination and filters
    async fn list_with_filters(&self, params: EmvQrConfigPaginationParams, filters: EmvQrConfigFilter) -> Result<EmvQrConfigPaginatedResult>;

    /// Count all emv_qr_config entities
    async fn count(&self) -> Result<u64>;

    /// Count emv_qr_config entities matching filters
    async fn count_with_filters(&self, filters: EmvQrConfigFilter) -> Result<u64>;

    /// Check if emv_qr_config exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save emv_qr_config entities
    async fn bulk_save(&self, entities: &[EmvQrConfig]) -> Result<Vec<EmvQrConfig>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
