//! Repository trait for Journal aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Journal aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Journal, JournalSource, JournalStatus, JournalType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct JournalPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl JournalPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct JournalPaginatedResult {
    pub data: Vec<Journal>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct JournalFilter {
    pub company_id: Option<Uuid>,
    pub journal_number: Option<String>,
    pub reference_number: Option<String>,
    pub journal_type: Option<JournalType>,
    pub branch_id: Option<Uuid>,
    pub fiscal_period_id: Option<Uuid>,
    pub description: Option<String>,
    pub notes: Option<String>,
    pub currency: Option<String>,
    pub source: Option<JournalSource>,
    pub source_type: Option<String>,
    pub source_id: Option<Uuid>,
    pub source_reference: Option<String>,
    pub is_reversed: Option<bool>,
    pub reversed_by_id: Option<Uuid>,
    pub reversal_reason: Option<String>,
    pub reverses_id: Option<Uuid>,
    pub is_reversing: Option<bool>,
    pub auto_reverse: Option<bool>,
    pub status: Option<JournalStatus>,
    pub requires_approval: Option<bool>,
    pub submitted_by: Option<Uuid>,
    pub approved_by: Option<Uuid>,
    pub rejected_by: Option<Uuid>,
    pub rejection_reason: Option<String>,
    pub posted_by: Option<Uuid>,
    pub is_voided: Option<bool>,
    pub voided_by: Option<Uuid>,
    pub void_reason: Option<String>,
}

impl JournalFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.journal_number.is_some() || self.reference_number.is_some() || self.journal_type.is_some() || self.branch_id.is_some() || self.fiscal_period_id.is_some() || self.description.is_some() || self.notes.is_some() || self.currency.is_some() || self.source.is_some() || self.source_type.is_some() || self.source_id.is_some() || self.source_reference.is_some() || self.is_reversed.is_some() || self.reversed_by_id.is_some() || self.reversal_reason.is_some() || self.reverses_id.is_some() || self.is_reversing.is_some() || self.auto_reverse.is_some() || self.status.is_some() || self.requires_approval.is_some() || self.submitted_by.is_some() || self.approved_by.is_some() || self.rejected_by.is_some() || self.rejection_reason.is_some() || self.posted_by.is_some() || self.is_voided.is_some() || self.voided_by.is_some() || self.void_reason.is_some()
    }
}

/// Repository trait for Journal aggregate
///
/// This trait defines the persistence contract for Journal entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait JournalRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new journal entity
    async fn save(&self, entity: &Journal) -> Result<Journal>;

    /// Find journal by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Journal>>;

    /// Find all journal entities
    async fn find_all(&self) -> Result<Vec<Journal>>;

    /// Update journal by ID
    async fn update(&self, id: &str, entity: &Journal) -> Result<Option<Journal>>;

    /// Delete journal by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List journal with pagination
    async fn list(&self, params: JournalPaginationParams) -> Result<JournalPaginatedResult>;

    /// List journal with pagination and filters
    async fn list_with_filters(&self, params: JournalPaginationParams, filters: JournalFilter) -> Result<JournalPaginatedResult>;

    /// Count all journal entities
    async fn count(&self) -> Result<u64>;

    /// Count journal entities matching filters
    async fn count_with_filters(&self, filters: JournalFilter) -> Result<u64>;

    /// Check if journal exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete journal by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted journal by ID
    async fn restore(&self, id: &str) -> Result<Option<Journal>>;

    /// List soft-deleted journal entities
    async fn list_deleted(&self, params: JournalPaginationParams) -> Result<JournalPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save journal entities
    async fn bulk_save(&self, entities: &[Journal]) -> Result<Vec<Journal>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
