//! Repository trait for JournalLine aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the JournalLine aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::JournalLine;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct JournalLinePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl JournalLinePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct JournalLinePaginatedResult {
    pub data: Vec<JournalLine>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct JournalLineFilter {
    pub journal_id: Option<Uuid>,
    pub provider_id: Option<Uuid>,
    pub outlet_id: Option<Uuid>,
    pub account_id: Option<Uuid>,
    pub account_number: Option<String>,
    pub account_name: Option<String>,
    pub currency: Option<String>,
    pub description: Option<String>,
    pub cost_center: Option<String>,
    pub project: Option<String>,
    pub department: Option<String>,
    pub source_type: Option<String>,
    pub source_id: Option<Uuid>,
    pub source_reference: Option<String>,
    pub is_tax_line: Option<bool>,
    pub related_line_id: Option<Uuid>,
    pub has_quantity: Option<bool>,
    pub unit: Option<String>,
    pub is_reconciled: Option<bool>,
    pub reconciliation_id: Option<Uuid>,
    pub is_posted: Option<bool>,
    pub ledger_id: Option<Uuid>,
}

impl JournalLineFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.journal_id.is_some() || self.provider_id.is_some() || self.outlet_id.is_some() || self.account_id.is_some() || self.account_number.is_some() || self.account_name.is_some() || self.currency.is_some() || self.description.is_some() || self.cost_center.is_some() || self.project.is_some() || self.department.is_some() || self.source_type.is_some() || self.source_id.is_some() || self.source_reference.is_some() || self.is_tax_line.is_some() || self.related_line_id.is_some() || self.has_quantity.is_some() || self.unit.is_some() || self.is_reconciled.is_some() || self.reconciliation_id.is_some() || self.is_posted.is_some() || self.ledger_id.is_some()
    }
}

/// Repository trait for JournalLine aggregate
///
/// This trait defines the persistence contract for JournalLine entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait JournalLineRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new journal_line entity
    async fn save(&self, entity: &JournalLine) -> Result<JournalLine>;

    /// Find journal_line by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<JournalLine>>;

    /// Find all journal_line entities
    async fn find_all(&self) -> Result<Vec<JournalLine>>;

    /// Update journal_line by ID
    async fn update(&self, id: &str, entity: &JournalLine) -> Result<Option<JournalLine>>;

    /// Delete journal_line by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List journal_line with pagination
    async fn list(&self, params: JournalLinePaginationParams) -> Result<JournalLinePaginatedResult>;

    /// List journal_line with pagination and filters
    async fn list_with_filters(&self, params: JournalLinePaginationParams, filters: JournalLineFilter) -> Result<JournalLinePaginatedResult>;

    /// Count all journal_line entities
    async fn count(&self) -> Result<u64>;

    /// Count journal_line entities matching filters
    async fn count_with_filters(&self, filters: JournalLineFilter) -> Result<u64>;

    /// Check if journal_line exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save journal_line entities
    async fn bulk_save(&self, entities: &[JournalLine]) -> Result<Vec<JournalLine>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
