//! Repository trait for ReconciliationItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ReconciliationItem aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{ReconciliationItem, ReconciliationItemStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ReconciliationItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ReconciliationItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ReconciliationItemPaginatedResult {
    pub data: Vec<ReconciliationItem>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ReconciliationItemFilter {
    pub reconciliation_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub source: Option<String>,
    pub ledger_id: Option<Uuid>,
    pub journal_id: Option<Uuid>,
    pub book_reference: Option<String>,
    pub book_description: Option<String>,
    pub statement_reference: Option<String>,
    pub statement_description: Option<String>,
    pub status: Option<ReconciliationItemStatus>,
    pub matched_with_id: Option<Uuid>,
    pub match_method: Option<String>,
    pub has_difference: Option<bool>,
    pub difference_reason: Option<String>,
    pub requires_adjustment: Option<bool>,
    pub adjustment_type: Option<String>,
    pub adjustment_journal_id: Option<Uuid>,
    pub is_written_off: Option<bool>,
    pub write_off_reason: Option<String>,
    pub write_off_approved_by: Option<Uuid>,
    pub is_outstanding: Option<bool>,
    pub outstanding_type: Option<String>,
    pub notes: Option<String>,
}

impl ReconciliationItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.reconciliation_id.is_some() || self.company_id.is_some() || self.source.is_some() || self.ledger_id.is_some() || self.journal_id.is_some() || self.book_reference.is_some() || self.book_description.is_some() || self.statement_reference.is_some() || self.statement_description.is_some() || self.status.is_some() || self.matched_with_id.is_some() || self.match_method.is_some() || self.has_difference.is_some() || self.difference_reason.is_some() || self.requires_adjustment.is_some() || self.adjustment_type.is_some() || self.adjustment_journal_id.is_some() || self.is_written_off.is_some() || self.write_off_reason.is_some() || self.write_off_approved_by.is_some() || self.is_outstanding.is_some() || self.outstanding_type.is_some() || self.notes.is_some()
    }
}

/// Repository trait for ReconciliationItem aggregate
///
/// This trait defines the persistence contract for ReconciliationItem entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ReconciliationItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new reconciliation_item entity
    async fn save(&self, entity: &ReconciliationItem) -> Result<ReconciliationItem>;

    /// Find reconciliation_item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ReconciliationItem>>;

    /// Find all reconciliation_item entities
    async fn find_all(&self) -> Result<Vec<ReconciliationItem>>;

    /// Update reconciliation_item by ID
    async fn update(&self, id: &str, entity: &ReconciliationItem) -> Result<Option<ReconciliationItem>>;

    /// Delete reconciliation_item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List reconciliation_item with pagination
    async fn list(&self, params: ReconciliationItemPaginationParams) -> Result<ReconciliationItemPaginatedResult>;

    /// List reconciliation_item with pagination and filters
    async fn list_with_filters(&self, params: ReconciliationItemPaginationParams, filters: ReconciliationItemFilter) -> Result<ReconciliationItemPaginatedResult>;

    /// Count all reconciliation_item entities
    async fn count(&self) -> Result<u64>;

    /// Count reconciliation_item entities matching filters
    async fn count_with_filters(&self, filters: ReconciliationItemFilter) -> Result<u64>;

    /// Check if reconciliation_item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save reconciliation_item entities
    async fn bulk_save(&self, entities: &[ReconciliationItem]) -> Result<Vec<ReconciliationItem>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
