//! Repository for BankCheckSequence entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<BankCheckSequence, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::BankCheckSequence;

/// Table name for BankCheckSequence entities
pub const TABLE_NAME: &str = "accounting.bank_check_sequences";

/// Repository for BankCheckSequence entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct BankCheckSequenceRepository(
    backbone_orm::GenericCrudRepository<BankCheckSequence, backbone_orm::HardDelete>,
);

impl std::ops::Deref for BankCheckSequenceRepository {
    type Target = backbone_orm::GenericCrudRepository<BankCheckSequence, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl BankCheckSequenceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(BankCheckSequenceRepository, BankCheckSequence, no_soft_delete);
