//! Repository for EmvQrConfig entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EmvQrConfig, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::EmvQrConfig;

/// Table name for EmvQrConfig entities
pub const TABLE_NAME: &str = "accounting.emv_qr_configs";

/// Repository for EmvQrConfig entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EmvQrConfigRepository(
    backbone_orm::GenericCrudRepository<EmvQrConfig, backbone_orm::HardDelete>,
);

impl std::ops::Deref for EmvQrConfigRepository {
    type Target = backbone_orm::GenericCrudRepository<EmvQrConfig, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EmvQrConfigRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(EmvQrConfigRepository, EmvQrConfig, no_soft_delete);
