//! Repository for FinancialStatement entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<FinancialStatement, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::FinancialStatement;

/// Table name for FinancialStatement entities
pub const TABLE_NAME: &str = "financial_statements";

/// Repository for FinancialStatement entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct FinancialStatementRepository(
    backbone_orm::GenericCrudRepository<FinancialStatement, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for FinancialStatementRepository {
    type Target = backbone_orm::GenericCrudRepository<FinancialStatement, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl FinancialStatementRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(FinancialStatementRepository, FinancialStatement, soft_delete);
