//! Repository for JournalLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<JournalLine, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::JournalLine;

/// Table name for JournalLine entities
pub const TABLE_NAME: &str = "accounting.journal_lines";

/// Repository for JournalLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct JournalLineRepository(
    backbone_orm::GenericCrudRepository<JournalLine, backbone_orm::HardDelete>,
);

impl std::ops::Deref for JournalLineRepository {
    type Target = backbone_orm::GenericCrudRepository<JournalLine, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl JournalLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(JournalLineRepository, JournalLine, no_soft_delete);
