//! Repository for Journal entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Journal, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Journal;

/// Table name for Journal entities
pub const TABLE_NAME: &str = "accounting.journals";

/// Repository for Journal entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct JournalRepository(
    backbone_orm::GenericCrudRepository<Journal, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for JournalRepository {
    type Target = backbone_orm::GenericCrudRepository<Journal, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl JournalRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(JournalRepository, Journal, soft_delete);
