//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod account_repository;
mod accounting_post_repository;
mod cost_center_repository;
mod financial_statement_repository;
mod fiscal_period_repository;
mod journal_repository;
mod journal_line_repository;
mod ledger_repository;
mod reconciliation_repository;
mod reconciliation_item_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use account_repository::AccountRepository;
pub use accounting_post_repository::AccountingPostRepository;
pub use cost_center_repository::CostCenterRepository;
pub use financial_statement_repository::FinancialStatementRepository;
pub use fiscal_period_repository::FiscalPeriodRepository;
pub use journal_repository::JournalRepository;
pub use journal_line_repository::JournalLineRepository;
pub use ledger_repository::LedgerRepository;
pub use reconciliation_repository::ReconciliationRepository;
pub use reconciliation_item_repository::ReconciliationItemRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
