//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod account_repository;
mod accounting_post_repository;
mod cost_center_repository;
mod emv_qr_config_repository;
mod bank_check_sequence_repository;
mod printed_check_repository;
mod tax_tag_repair_run_repository;
mod financial_statement_repository;
mod fiscal_period_repository;
mod journal_repository;
mod journal_line_repository;
mod ledger_repository;
mod reconciliation_repository;
mod reconciliation_item_repository;
mod full_reconcile_repository;
mod partial_reconcile_repository;

// Custom persistence modules
// <<< CUSTOM
pub mod bank_reconciliation_repository;
pub mod chart_install_repository;
pub mod hierarchy_repository;
pub mod journal_workflow_repository;
pub mod period_close_repository;
pub mod posting_repository;
pub mod reconcile_graph_repository;
pub mod reporting_repository;
// END CUSTOM

// Re-exports
pub use account_repository::AccountRepository;
pub use accounting_post_repository::AccountingPostRepository;
pub use cost_center_repository::CostCenterRepository;
pub use emv_qr_config_repository::EmvQrConfigRepository;
pub use bank_check_sequence_repository::BankCheckSequenceRepository;
pub use printed_check_repository::PrintedCheckRepository;
pub use tax_tag_repair_run_repository::TaxTagRepairRunRepository;
pub use financial_statement_repository::FinancialStatementRepository;
pub use fiscal_period_repository::FiscalPeriodRepository;
pub use journal_repository::JournalRepository;
pub use journal_line_repository::JournalLineRepository;
pub use ledger_repository::LedgerRepository;
pub use reconciliation_repository::ReconciliationRepository;
pub use reconciliation_item_repository::ReconciliationItemRepository;
pub use full_reconcile_repository::FullReconcileRepository;
pub use partial_reconcile_repository::PartialReconcileRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use bank_reconciliation_repository::SqlxBankReconciliationRepository;
pub use chart_install_repository::SqlxChartInstallRepository;
pub use hierarchy_repository::SqlxHierarchyRepository;
pub use journal_workflow_repository::SqlxJournalWorkflowRepository;
pub use period_close_repository::SqlxPeriodCloseRepository;
pub use posting_repository::SqlxPostingRepository;
pub use reconcile_graph_repository::SqlxReconcileGraphRepository;
pub use reporting_repository::SqlxReportingRepository;
// END CUSTOM
