//! Repository for PartialReconcile entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PartialReconcile, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PartialReconcile;

/// Table name for PartialReconcile entities
pub const TABLE_NAME: &str = "accounting.partial_reconciles";

/// Repository for PartialReconcile entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PartialReconcileRepository(
    backbone_orm::GenericCrudRepository<PartialReconcile, backbone_orm::HardDelete>,
);

impl std::ops::Deref for PartialReconcileRepository {
    type Target = backbone_orm::GenericCrudRepository<PartialReconcile, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl PartialReconcileRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PartialReconcileRepository, PartialReconcile, no_soft_delete);
