//! Validator for JournalLine entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<JournalLine>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::JournalLine;

/// Validator type alias for JournalLine entities.
pub type JournalLineValidator = EntityValidator<JournalLine>;

/// Build a validator for JournalLine with all schema-defined field rules.
pub fn journal_line_validator() -> JournalLineValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("journal_id", |e: &JournalLine| &e.journal_id))
        .rule(RequiredUuid::new("account_id", |e: &JournalLine| &e.account_id))
        .rule(RequiredString::new("account_number", |e: &JournalLine| &e.account_number))
        .rule(RequiredString::new("account_name", |e: &JournalLine| &e.account_name))
        .rule(NonNegative::new("debit_amount", |e: &JournalLine| e.debit_amount))
        .rule(NonNegative::new("credit_amount", |e: &JournalLine| e.credit_amount))
        .rule(RequiredString::new("currency", |e: &JournalLine| &e.currency))
        .rule(NonNegative::new("base_debit_amount", |e: &JournalLine| e.base_debit_amount))
        .rule(NonNegative::new("base_credit_amount", |e: &JournalLine| e.base_credit_amount))
        .rule(OptionalNotBlank::new("description", |e: &JournalLine| e.description.as_deref()))
        .rule(OptionalNotBlank::new("cost_center", |e: &JournalLine| e.cost_center.as_deref()))
        .rule(OptionalNotBlank::new("project", |e: &JournalLine| e.project.as_deref()))
        .rule(OptionalNotBlank::new("department", |e: &JournalLine| e.department.as_deref()))
        .rule(OptionalNotBlank::new("source_type", |e: &JournalLine| e.source_type.as_deref()))
        .rule(OptionalNotBlank::new("source_reference", |e: &JournalLine| e.source_reference.as_deref()))
        .rule(NonNegative::new("tax_base_amount", |e: &JournalLine| e.tax_base_amount))
        .rule(OptionalNotBlank::new("unit", |e: &JournalLine| e.unit.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
