//! Auth configuration for CostCenter handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<CostCenter>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CostCenterService;
use crate::domain::entity::CostCenter;

/// Permission string constants for CostCenter operations.
pub mod permissions {
    pub const LIST:        &str = "cost_center:list";
    pub const READ:        &str = "cost_center:read";
    pub const CREATE:      &str = "cost_center:create";
    pub const UPDATE:      &str = "cost_center:update";
    pub const DELETE:      &str = "cost_center:delete";
    pub const RESTORE:     &str = "cost_center:restore";
    pub const TRASH:       &str = "cost_center:trash";
    pub const EMPTY_TRASH: &str = "cost_center:empty_trash";
    pub const BULK_CREATE: &str = "cost_center:bulk_create";
    pub const UPSERT:      &str = "cost_center:upsert";
}

/// Resource policy for CostCenter — maps CRUD actions to permission strings.
pub struct CostCenterPolicy;

#[async_trait]
impl ResourcePolicy<CostCenter> for CostCenterPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &CostCenter,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for CostCenter handlers.
///
/// Wraps `CostCenterService` and checks `CostCenterPolicy` before delegating.
pub type CostCenterGuard = PermissionGuard<CostCenter>;

/// Service-integrated permission guard for CostCenter (for use in generated handlers).
pub type CostCenterServiceGuard = ServicePermissionGuard<CostCenter, CostCenterService, CostCenterPolicy>;

// <<< CUSTOM
// END CUSTOM
