//! Auth configuration for FinancialStatement handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<FinancialStatement>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::FinancialStatementService;
use crate::domain::entity::FinancialStatement;

/// Permission string constants for FinancialStatement operations.
pub mod permissions {
    pub const LIST:        &str = "financial_statement:list";
    pub const READ:        &str = "financial_statement:read";
    pub const CREATE:      &str = "financial_statement:create";
    pub const UPDATE:      &str = "financial_statement:update";
    pub const DELETE:      &str = "financial_statement:delete";
    pub const RESTORE:     &str = "financial_statement:restore";
    pub const TRASH:       &str = "financial_statement:trash";
    pub const EMPTY_TRASH: &str = "financial_statement:empty_trash";
    pub const BULK_CREATE: &str = "financial_statement:bulk_create";
    pub const UPSERT:      &str = "financial_statement:upsert";
}

/// Resource policy for FinancialStatement — maps CRUD actions to permission strings.
pub struct FinancialStatementPolicy;

#[async_trait]
impl ResourcePolicy<FinancialStatement> for FinancialStatementPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &FinancialStatement,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for FinancialStatement handlers.
///
/// Wraps `FinancialStatementService` and checks `FinancialStatementPolicy` before delegating.
pub type FinancialStatementGuard = PermissionGuard<FinancialStatement>;

/// Service-integrated permission guard for FinancialStatement (for use in generated handlers).
pub type FinancialStatementServiceGuard = ServicePermissionGuard<FinancialStatement, FinancialStatementService, FinancialStatementPolicy>;

// <<< CUSTOM
// END CUSTOM
