//! Auth configuration for JournalLine handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<JournalLine>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::JournalLineService;
use crate::domain::entity::JournalLine;

/// Permission string constants for JournalLine operations.
pub mod permissions {
    pub const LIST:        &str = "journal_line:list";
    pub const READ:        &str = "journal_line:read";
    pub const CREATE:      &str = "journal_line:create";
    pub const UPDATE:      &str = "journal_line:update";
    pub const DELETE:      &str = "journal_line:delete";
    pub const RESTORE:     &str = "journal_line:restore";
    pub const TRASH:       &str = "journal_line:trash";
    pub const EMPTY_TRASH: &str = "journal_line:empty_trash";
    pub const BULK_CREATE: &str = "journal_line:bulk_create";
    pub const UPSERT:      &str = "journal_line:upsert";
}

/// Resource policy for JournalLine — maps CRUD actions to permission strings.
pub struct JournalLinePolicy;

#[async_trait]
impl ResourcePolicy<JournalLine> for JournalLinePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &JournalLine,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for JournalLine handlers.
///
/// Wraps `JournalLineService` and checks `JournalLinePolicy` before delegating.
pub type JournalLineGuard = PermissionGuard<JournalLine>;

/// Service-integrated permission guard for JournalLine (for use in generated handlers).
pub type JournalLineServiceGuard = ServicePermissionGuard<JournalLine, JournalLineService, JournalLinePolicy>;

// <<< CUSTOM
// END CUSTOM
