//! AccountingPost API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the AccountingPost CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ACCOUNTINGPOST TEST DATA GENERATOR
// ============================================================================

/// Test data generator for AccountingPost
pub struct AccountingPostTestData;

impl TestDataGenerator for AccountingPostTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "source_type": "order",
            "source_id": Uuid::new_v4().to_string(),
            "source_reference": null,
            "journal_id": null,
            "posting_type": "original",
            "posting_status": "pending",
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "total_debit": 0,
            "total_credit": 0,
            "scheduled_at": now,
            "posted_at": now,
            "failed_at": now,
            "retry_count": 1,
            "max_retries": 1,
            "next_retry_at": now,
            "error_code": null,
            "error_message": null,
            "reverses_post_id": null,
            "reversed_by_post_id": null,
            "posted_by": null,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "branch_id": null,
            "source_type": "order",
            "source_id": Uuid::new_v4().to_string(),
            "source_reference": null,
            "journal_id": null,
            "posting_type": "original",
            "posting_status": "pending",
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "total_debit": 0,
            "total_credit": 0,
            "scheduled_at": now,
            "posted_at": now,
            "failed_at": now,
            "retry_count": 1,
            "max_retries": 1,
            "next_retry_at": now,
            "error_code": null,
            "error_message": null,
            "reverses_post_id": null,
            "reversed_by_post_id": null,
            "posted_by": null,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ACCOUNTINGPOST API TEST
// ============================================================================

/// AccountingPost API test suite
pub struct AccountingPostApiTest {
    inner: GenericCrudTest<AccountingPostTestData>,
}

impl AccountingPostApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/accounting_posts", "AccountingPost");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, AccountingPostTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AccountingPostApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_accounting_post_crud() {
        let mut test = AccountingPostApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add AccountingPost specific tests here
// <<< CUSTOM TESTS END >>>
