//! FinancialStatement API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the FinancialStatement CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// FINANCIALSTATEMENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for FinancialStatement
pub struct FinancialStatementTestData;

impl TestDataGenerator for FinancialStatementTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "statement_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "statement_type": "balance_sheet",
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "fiscal_period_id": null,
            "fiscal_year": 1,
            "fiscal_month": null,
            "as_of_date": Utc::now().format("%Y-%m-%d").to_string(),
            "period_start": null,
            "period_end": null,
            "is_comparative": false,
            "comparative_period_id": null,
            "comparative_as_of_date": null,
            "status": "draft",
            "total_current_assets": null,
            "total_non_current_assets": null,
            "total_assets": null,
            "total_current_liabilities": null,
            "total_non_current_liabilities": null,
            "total_liabilities": null,
            "total_equity": null,
            "balance_check": false,
            "balance_difference": null,
            "total_revenue": null,
            "total_cogs": null,
            "gross_profit": null,
            "gross_profit_margin": null,
            "total_operating_expenses": null,
            "operating_income": null,
            "operating_margin": null,
            "total_other_income": null,
            "total_other_expenses": null,
            "income_before_tax": null,
            "tax_expense": null,
            "net_income": null,
            "net_profit_margin": null,
            "cash_from_operations": null,
            "cash_from_investing": null,
            "cash_from_financing": null,
            "net_cash_change": null,
            "beginning_cash": null,
            "ending_cash": null,
            "total_debits": null,
            "total_credits": null,
            "trial_balance_check": false,
            "line_items": json!({}),
            "comparative_data": json!({}),
            "variance_data": json!({}),
            "notes": json!({}),
            "management_notes": null,
            "generated_at": now,
            "generated_by": null,
            "generation_parameters": json!({}),
            "reviewed_at": now,
            "reviewed_by": null,
            "approved_at": now,
            "approved_by": null,
            "published_at": now,
            "pdf_url": null,
            "excel_url": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "statement_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "statement_type": "balance_sheet",
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "fiscal_period_id": null,
            "fiscal_year": 1,
            "fiscal_month": null,
            "as_of_date": Utc::now().format("%Y-%m-%d").to_string(),
            "period_start": null,
            "period_end": null,
            "is_comparative": false,
            "comparative_period_id": null,
            "comparative_as_of_date": null,
            "status": "draft",
            "total_current_assets": null,
            "total_non_current_assets": null,
            "total_assets": null,
            "total_current_liabilities": null,
            "total_non_current_liabilities": null,
            "total_liabilities": null,
            "total_equity": null,
            "balance_check": false,
            "balance_difference": null,
            "total_revenue": null,
            "total_cogs": null,
            "gross_profit": null,
            "gross_profit_margin": null,
            "total_operating_expenses": null,
            "operating_income": null,
            "operating_margin": null,
            "total_other_income": null,
            "total_other_expenses": null,
            "income_before_tax": null,
            "tax_expense": null,
            "net_income": null,
            "net_profit_margin": null,
            "cash_from_operations": null,
            "cash_from_investing": null,
            "cash_from_financing": null,
            "net_cash_change": null,
            "beginning_cash": null,
            "ending_cash": null,
            "total_debits": null,
            "total_credits": null,
            "trial_balance_check": false,
            "line_items": json!({}),
            "comparative_data": json!({}),
            "variance_data": json!({}),
            "notes": json!({}),
            "management_notes": null,
            "generated_at": now,
            "generated_by": null,
            "generation_parameters": json!({}),
            "reviewed_at": now,
            "reviewed_by": null,
            "approved_at": now,
            "approved_by": null,
            "published_at": now,
            "pdf_url": null,
            "excel_url": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// FINANCIALSTATEMENT API TEST
// ============================================================================

/// FinancialStatement API test suite
pub struct FinancialStatementApiTest {
    inner: GenericCrudTest<FinancialStatementTestData>,
}

impl FinancialStatementApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/financial_statements", "FinancialStatement");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, FinancialStatementTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for FinancialStatementApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_financial_statement_crud() {
        let mut test = FinancialStatementApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add FinancialStatement specific tests here
// <<< CUSTOM TESTS END >>>
