//! Journal API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Journal CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// JOURNAL TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Journal
pub struct JournalTestData;

impl TestDataGenerator for JournalTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "journal_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "reference_number": null,
            "journal_type": "general",
            "branch_id": null,
            "transaction_date": Utc::now().format("%Y-%m-%d").to_string(),
            "posting_date": null,
            "fiscal_period_id": null,
            "fiscal_year": null,
            "fiscal_month": null,
            "description": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "notes": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "total_debit": 0,
            "total_credit": 0,
            "line_count": 1,
            "source": "manual",
            "source_type": null,
            "source_id": null,
            "source_reference": null,
            "is_reversed": false,
            "reversed_by_id": null,
            "reversed_at": now,
            "reversal_reason": null,
            "reverses_id": null,
            "is_reversing": false,
            "auto_reverse": false,
            "auto_reverse_date": null,
            "status": "draft",
            "requires_approval": false,
            "approval_threshold": null,
            "submitted_at": now,
            "submitted_by": null,
            "approved_at": now,
            "approved_by": null,
            "rejected_at": now,
            "rejected_by": null,
            "rejection_reason": null,
            "posted_at": now,
            "posted_by": null,
            "is_voided": false,
            "voided_at": now,
            "voided_by": null,
            "void_reason": null,
            "attachments": json!({}),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "journal_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "reference_number": null,
            "journal_type": "general",
            "branch_id": null,
            "transaction_date": Utc::now().format("%Y-%m-%d").to_string(),
            "posting_date": null,
            "fiscal_period_id": null,
            "fiscal_year": null,
            "fiscal_month": null,
            "description": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "notes": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "total_debit": 0,
            "total_credit": 0,
            "line_count": 1,
            "source": "manual",
            "source_type": null,
            "source_id": null,
            "source_reference": null,
            "is_reversed": false,
            "reversed_by_id": null,
            "reversed_at": now,
            "reversal_reason": null,
            "reverses_id": null,
            "is_reversing": false,
            "auto_reverse": false,
            "auto_reverse_date": null,
            "status": "draft",
            "requires_approval": false,
            "approval_threshold": null,
            "submitted_at": now,
            "submitted_by": null,
            "approved_at": now,
            "approved_by": null,
            "rejected_at": now,
            "rejected_by": null,
            "rejection_reason": null,
            "posted_at": now,
            "posted_by": null,
            "is_voided": false,
            "voided_at": now,
            "voided_by": null,
            "void_reason": null,
            "attachments": json!({}),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// JOURNAL API TEST
// ============================================================================

/// Journal API test suite
pub struct JournalApiTest {
    inner: GenericCrudTest<JournalTestData>,
}

impl JournalApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/journals", "Journal");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, JournalTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for JournalApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_journal_crud() {
        let mut test = JournalApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Journal specific tests here
// <<< CUSTOM TESTS END >>>
