//! Ledger API Integration Tests
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Tests the Ledger CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// LEDGER TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Ledger
pub struct LedgerTestData;

impl TestDataGenerator for LedgerTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "provider_id": null,
            "account_id": null,
            "account_number": null,
            "account_name": null,
            "account_type": null,
            "normal_balance": null,
            "journal_id": null,
            "journal_number": null,
            "journal_line_id": null,
            "transaction_date": null,
            "posting_date": null,
            "fiscal_period_id": null,
            "fiscal_year": null,
            "fiscal_month": null,
            "description": "Test description",
            "reference": null,
            "currency": null,
            "debit_amount": null,
            "credit_amount": null,
            "balance_before": null,
            "balance_after": null,
            "balance_change": null,
            "sequence_number": null,
            "outlet_id": null,
            "cost_center": null,
            "project": null,
            "department": null,
            "source_type": null,
            "source_id": null,
            "source_reference": null,
            "is_reconciled": false,
            "reconciliation_id": null,
            "reconciled_at": now,
            "is_opening_balance": false,
            "is_closing_entry": false,
            "is_adjustment": false,
            "is_reversed": false,
            "reversed_by_id": null,
            "reverses_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "provider_id": null,
            "account_id": null,
            "account_number": null,
            "account_name": null,
            "account_type": null,
            "normal_balance": null,
            "journal_id": null,
            "journal_number": null,
            "journal_line_id": null,
            "transaction_date": null,
            "posting_date": null,
            "fiscal_period_id": null,
            "fiscal_year": null,
            "fiscal_month": null,
            "description": "Test description",
            "reference": null,
            "currency": null,
            "debit_amount": null,
            "credit_amount": null,
            "balance_before": null,
            "balance_after": null,
            "balance_change": null,
            "sequence_number": null,
            "outlet_id": null,
            "cost_center": null,
            "project": null,
            "department": null,
            "source_type": null,
            "source_id": null,
            "source_reference": null,
            "is_reconciled": false,
            "reconciliation_id": null,
            "reconciled_at": now,
            "is_opening_balance": false,
            "is_closing_entry": false,
            "is_adjustment": false,
            "is_reversed": false,
            "reversed_by_id": null,
            "reverses_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// LEDGER API TEST
// ============================================================================

/// Ledger API test suite
pub struct LedgerApiTest {
    inner: GenericCrudTest<LedgerTestData>,
}

impl LedgerApiTest {
    pub fn new() -> Self {
        let config = CrudTestConfig::new("/api/v1/ledgers", "Ledger");
        Self {
            inner: GenericCrudTest::new(config, LedgerTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for LedgerApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_ledger_crud() {
        let mut test = LedgerApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Ledger specific tests here
// <<< CUSTOM TESTS END >>>
