//! ReconciliationItem API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ReconciliationItem CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// RECONCILIATIONITEM TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ReconciliationItem
pub struct ReconciliationItemTestData;

impl TestDataGenerator for ReconciliationItemTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "reconciliation_id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "item_number": 1,
            "source": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "ledger_id": null,
            "journal_id": null,
            "book_date": null,
            "book_reference": null,
            "book_description": null,
            "book_debit": 0,
            "book_credit": 0,
            "statement_date": null,
            "statement_reference": null,
            "statement_description": null,
            "statement_debit": 0,
            "statement_credit": 0,
            "status": "unmatched",
            "matched_with_id": null,
            "match_date": null,
            "match_method": null,
            "match_confidence": null,
            "has_difference": false,
            "difference_amount": 0,
            "difference_reason": null,
            "requires_adjustment": false,
            "adjustment_type": null,
            "adjustment_journal_id": null,
            "adjusted_at": now,
            "is_written_off": false,
            "write_off_reason": null,
            "write_off_approved_by": null,
            "is_outstanding": false,
            "outstanding_type": null,
            "expected_clear_date": null,
            "notes": null,
            "data": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "reconciliation_id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "item_number": 1,
            "source": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "ledger_id": null,
            "journal_id": null,
            "book_date": null,
            "book_reference": null,
            "book_description": null,
            "book_debit": 0,
            "book_credit": 0,
            "statement_date": null,
            "statement_reference": null,
            "statement_description": null,
            "statement_debit": 0,
            "statement_credit": 0,
            "status": "unmatched",
            "matched_with_id": null,
            "match_date": null,
            "match_method": null,
            "match_confidence": null,
            "has_difference": false,
            "difference_amount": 0,
            "difference_reason": null,
            "requires_adjustment": false,
            "adjustment_type": null,
            "adjustment_journal_id": null,
            "adjusted_at": now,
            "is_written_off": false,
            "write_off_reason": null,
            "write_off_approved_by": null,
            "is_outstanding": false,
            "outstanding_type": null,
            "expected_clear_date": null,
            "notes": null,
            "data": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/reconciliations", &super::reconciliation_api_test::ReconciliationTestData).await {
            deps.push(("reconciliation_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// RECONCILIATIONITEM API TEST
// ============================================================================

/// ReconciliationItem API test suite
pub struct ReconciliationItemApiTest {
    inner: GenericCrudTest<ReconciliationItemTestData>,
}

impl ReconciliationItemApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/reconciliation_items", "ReconciliationItem");
        config.supports_soft_delete = false;
        Self {
            inner: GenericCrudTest::new(config, ReconciliationItemTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ReconciliationItemApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_reconciliation_item_crud() {
        let mut test = ReconciliationItemApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ReconciliationItem specific tests here
// <<< CUSTOM TESTS END >>>
