//! Accounting Module Handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::AccountService;
use crate::application::service::AccountingPostService;
use crate::application::service::FinancialStatementService;
use crate::application::service::FiscalPeriodService;
use crate::application::service::JournalService;
use crate::application::service::JournalLineService;
use crate::application::service::LedgerService;
use crate::application::service::ReconciliationService;
use crate::application::service::ReconciliationItemService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Account service
    pub account_service: Arc<AccountService>,
    /// AccountingPost service
    pub accounting_post_service: Arc<AccountingPostService>,
    /// FinancialStatement service
    pub financial_statement_service: Arc<FinancialStatementService>,
    /// FiscalPeriod service
    pub fiscal_period_service: Arc<FiscalPeriodService>,
    /// Journal service
    pub journal_service: Arc<JournalService>,
    /// JournalLine service
    pub journal_line_service: Arc<JournalLineService>,
    /// Ledger service
    pub ledger_service: Arc<LedgerService>,
    /// Reconciliation service
    pub reconciliation_service: Arc<ReconciliationService>,
    /// ReconciliationItem service
    pub reconciliation_item_service: Arc<ReconciliationItemService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        account_service: Arc<AccountService>,
        accounting_post_service: Arc<AccountingPostService>,
        financial_statement_service: Arc<FinancialStatementService>,
        fiscal_period_service: Arc<FiscalPeriodService>,
        journal_service: Arc<JournalService>,
        journal_line_service: Arc<JournalLineService>,
        ledger_service: Arc<LedgerService>,
        reconciliation_service: Arc<ReconciliationService>,
        reconciliation_item_service: Arc<ReconciliationItemService>
    ) -> Self {
        Self {
            account_service,
            accounting_post_service,
            financial_statement_service,
            fiscal_period_service,
            journal_service,
            journal_line_service,
            ledger_service,
            reconciliation_service,
            reconciliation_item_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::AccountingModule) -> Self {
        Self {
            account_service: module.account_service.clone(),
            accounting_post_service: module.accounting_post_service.clone(),
            financial_statement_service: module.financial_statement_service.clone(),
            fiscal_period_service: module.fiscal_period_service.clone(),
            journal_service: module.journal_service.clone(),
            journal_line_service: module.journal_line_service.clone(),
            ledger_service: module.ledger_service.clone(),
            reconciliation_service: module.reconciliation_service.clone(),
            reconciliation_item_service: module.reconciliation_item_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    account_service: Option<Arc<AccountService>>,
    accounting_post_service: Option<Arc<AccountingPostService>>,
    financial_statement_service: Option<Arc<FinancialStatementService>>,
    fiscal_period_service: Option<Arc<FiscalPeriodService>>,
    journal_service: Option<Arc<JournalService>>,
    journal_line_service: Option<Arc<JournalLineService>>,
    ledger_service: Option<Arc<LedgerService>>,
    reconciliation_service: Option<Arc<ReconciliationService>>,
    reconciliation_item_service: Option<Arc<ReconciliationItemService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Account service.
    pub fn with_account_service(mut self, service: Arc<AccountService>) -> Self {
        self.account_service = Some(service);
        self
    }

    /// Set the AccountingPost service.
    pub fn with_accounting_post_service(mut self, service: Arc<AccountingPostService>) -> Self {
        self.accounting_post_service = Some(service);
        self
    }

    /// Set the FinancialStatement service.
    pub fn with_financial_statement_service(mut self, service: Arc<FinancialStatementService>) -> Self {
        self.financial_statement_service = Some(service);
        self
    }

    /// Set the FiscalPeriod service.
    pub fn with_fiscal_period_service(mut self, service: Arc<FiscalPeriodService>) -> Self {
        self.fiscal_period_service = Some(service);
        self
    }

    /// Set the Journal service.
    pub fn with_journal_service(mut self, service: Arc<JournalService>) -> Self {
        self.journal_service = Some(service);
        self
    }

    /// Set the JournalLine service.
    pub fn with_journal_line_service(mut self, service: Arc<JournalLineService>) -> Self {
        self.journal_line_service = Some(service);
        self
    }

    /// Set the Ledger service.
    pub fn with_ledger_service(mut self, service: Arc<LedgerService>) -> Self {
        self.ledger_service = Some(service);
        self
    }

    /// Set the Reconciliation service.
    pub fn with_reconciliation_service(mut self, service: Arc<ReconciliationService>) -> Self {
        self.reconciliation_service = Some(service);
        self
    }

    /// Set the ReconciliationItem service.
    pub fn with_reconciliation_item_service(mut self, service: Arc<ReconciliationItemService>) -> Self {
        self.reconciliation_item_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            account_service: self.account_service.expect("account_service is required"),
            accounting_post_service: self.accounting_post_service.expect("accounting_post_service is required"),
            financial_statement_service: self.financial_statement_service.expect("financial_statement_service is required"),
            fiscal_period_service: self.fiscal_period_service.expect("fiscal_period_service is required"),
            journal_service: self.journal_service.expect("journal_service is required"),
            journal_line_service: self.journal_line_service.expect("journal_line_service is required"),
            ledger_service: self.ledger_service.expect("ledger_service is required"),
            reconciliation_service: self.reconciliation_service.expect("reconciliation_service is required"),
            reconciliation_item_service: self.reconciliation_item_service.expect("reconciliation_item_service is required"),
        }
    }
}
