//! Accounting Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod application;
pub mod domain;
pub mod exports;
pub mod infrastructure;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AccountService;
pub use application::service::AccountingPostService;
pub use application::service::CostCenterService;
pub use application::service::FinancialStatementService;
pub use application::service::FiscalPeriodService;
pub use application::service::FullReconcileService;
pub use application::service::JournalLineService;
pub use application::service::JournalService;
pub use application::service::LedgerService;
pub use application::service::PartialReconcileService;
pub use application::service::ReconciliationItemService;
pub use application::service::ReconciliationService;

// Re-exports - Workflows
pub use application::workflows::*;

use axum::Router;
use sqlx::PgPool;
use std::sync::Arc;

/// Accounting module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let accounting = AccountingModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = accounting.all_crud_routes();
/// ```
pub struct AccountingModule {
    pub(crate) account_service: Arc<AccountService>,
    pub(crate) accounting_post_service: Arc<AccountingPostService>,
    pub(crate) cost_center_service: Arc<CostCenterService>,
    pub(crate) financial_statement_service: Arc<FinancialStatementService>,
    pub(crate) fiscal_period_service: Arc<FiscalPeriodService>,
    pub(crate) journal_service: Arc<JournalService>,
    pub(crate) journal_line_service: Arc<JournalLineService>,
    pub(crate) ledger_service: Arc<LedgerService>,
    pub(crate) reconciliation_service: Arc<ReconciliationService>,
    pub(crate) reconciliation_item_service: Arc<ReconciliationItemService>,
    pub(crate) full_reconcile_service: Arc<FullReconcileService>,
    pub(crate) partial_reconcile_service: Arc<PartialReconcileService>,
    // <<< CUSTOM FIELDS
    pub(crate) db_pool: PgPool,
    pub(crate) reconcile_write_service:
        Arc<crate::application::service::reconcile_write_service::ReconcileWriteService>,
    /// Host-implemented cash-basis tax deferral lookup, kept so post-build
    /// service variants (e.g. the exchange-account one) keep the flip wired.
    pub(crate) deferred_tax: Option<Arc<dyn crate::domain::repositories::DeferredTaxLookup>>,
    /// Chart install engine over the datasets registered via `with_chart_dataset`.
    pub(crate) chart_install_service:
        Arc<crate::application::service::chart_install_service::ChartInstallService>,
    // END CUSTOM
}

impl AccountingModule {
    /// Create a new module builder
    pub fn builder() -> AccountingModuleBuilder {
        AccountingModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_account_routes, create_accounting_post_routes, create_cost_center_routes,
            create_financial_statement_routes, create_fiscal_period_routes,
            create_full_reconcile_routes, create_journal_line_routes, create_journal_routes,
            create_ledger_routes, create_partial_reconcile_routes,
            create_reconciliation_item_routes, create_reconciliation_routes,
        };

        Router::new()
            .merge(create_account_routes(self.account_service.clone()))
            .merge(create_accounting_post_routes(
                self.accounting_post_service.clone(),
            ))
            .merge(create_cost_center_routes(self.cost_center_service.clone()))
            .merge(create_financial_statement_routes(
                self.financial_statement_service.clone(),
            ))
            .merge(create_fiscal_period_routes(
                self.fiscal_period_service.clone(),
            ))
            .merge(create_journal_routes(self.journal_service.clone()))
            .merge(create_journal_line_routes(
                self.journal_line_service.clone(),
            ))
            .merge(create_ledger_routes(self.ledger_service.clone()))
            .merge(create_reconciliation_routes(
                self.reconciliation_service.clone(),
            ))
            .merge(create_reconciliation_item_routes(
                self.reconciliation_item_service.clone(),
            ))
            .merge(create_full_reconcile_routes(
                self.full_reconcile_service.clone(),
            ))
            .merge(create_partial_reconcile_routes(
                self.partial_reconcile_service.clone(),
            ))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(
        note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface"
    )]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_account_read_routes, create_accounting_post_read_routes,
            create_cost_center_read_routes, create_financial_statement_read_routes,
            create_fiscal_period_read_routes, create_full_reconcile_read_routes,
            create_journal_line_read_routes, create_journal_read_routes, create_ledger_read_routes,
            create_partial_reconcile_read_routes, create_reconciliation_item_read_routes,
            create_reconciliation_read_routes,
        };

        Router::new()
            .merge(create_account_read_routes(self.account_service.clone()))
            .merge(create_accounting_post_read_routes(
                self.accounting_post_service.clone(),
            ))
            .merge(create_cost_center_read_routes(
                self.cost_center_service.clone(),
            ))
            .merge(create_financial_statement_read_routes(
                self.financial_statement_service.clone(),
            ))
            .merge(create_fiscal_period_read_routes(
                self.fiscal_period_service.clone(),
            ))
            .merge(create_journal_read_routes(self.journal_service.clone()))
            .merge(create_journal_line_read_routes(
                self.journal_line_service.clone(),
            ))
            .merge(create_ledger_read_routes(self.ledger_service.clone()))
            .merge(create_reconciliation_read_routes(
                self.reconciliation_service.clone(),
            ))
            .merge(create_reconciliation_item_read_routes(
                self.reconciliation_item_service.clone(),
            ))
            .merge(create_full_reconcile_read_routes(
                self.full_reconcile_service.clone(),
            ))
            .merge(create_partial_reconcile_read_routes(
                self.partial_reconcile_service.clone(),
            ))
    }

    // <<< CUSTOM METHODS
    /// The reconciliation write service — the ONLY sanctioned writer of the
    /// reconciliation graph (guards + CLAMP + side-effecting unlink). The graph tables
    /// carry no CRUD surface anywhere; `guarded_routes` mounts its verb routes.
    pub fn reconcile_write_service(
        &self,
    ) -> std::sync::Arc<crate::application::service::reconcile_write_service::ReconcileWriteService>
    {
        self.reconcile_write_service.clone()
    }

    /// Build a reconcile write service with the FX (exchange-difference) account
    /// configured. Without one, any rate divergence that demands an exchange move fails
    /// closed (`exchange_account_unconfigured`) — normal single-currency posts never
    /// generate one, so the default service is complete for them.
    pub fn reconcile_write_service_with_exchange_account(
        &self,
        exchange_account_id: uuid::Uuid,
    ) -> std::sync::Arc<crate::application::service::reconcile_write_service::ReconcileWriteService>
    {
        std::sync::Arc::new(
            crate::application::service::reconcile_write_service::ReconcileWriteService::new(
                std::sync::Arc::new(
                    crate::infrastructure::persistence::reconcile_graph_repository::SqlxReconcileGraphRepository::new(),
                ),
                std::sync::Arc::new(
                    crate::infrastructure::persistence::posting_repository::SqlxPostingRepository::new(
                        self.db_pool.clone(),
                    ),
                ),
                self.db_pool.clone(),
                Some(exchange_account_id),
            )
            .with_deferred_tax_if_set(self.deferred_tax.clone()),
        )
    }

    /// The chart install engine — validates, gates, and writes a registered chart
    /// dataset into one company's accounts, idempotently. The install VERB itself is
    /// host-mounted (it orchestrates beyond this module); this handle is the engine
    /// the host verb drives.
    pub fn chart_install_service(
        &self,
    ) -> std::sync::Arc<crate::application::service::chart_install_service::ChartInstallService>
    {
        self.chart_install_service.clone()
    }
    // END CUSTOM
}

/// Builder for AccountingModule
pub struct AccountingModuleBuilder {
    db_pool: Option<PgPool>,
    // <<< CUSTOM FIELDS
    deferred_tax: Option<Arc<dyn crate::domain::repositories::DeferredTaxLookup>>,
    chart_datasets: Vec<Arc<crate::domain::chart_dataset::ChartDataset>>,
    // END CUSTOM
}

impl AccountingModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
            // <<< CUSTOM INIT
            deferred_tax: None,
            chart_datasets: Vec::new(),
            // END CUSTOM
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    /// Register a chart-of-accounts dataset installable through the chart install
    /// engine. Datasets are data (commonly shipped by an l10n module); registering
    /// one makes it listable via `GET /accounting/charts` and installable by the
    /// host-mounted install verb.
    pub fn with_chart_dataset(
        mut self,
        dataset: Arc<crate::domain::chart_dataset::ChartDataset>,
    ) -> Self {
        self.chart_datasets.push(dataset);
        self
    }

    /// Wire the host's cash-basis tax deferral lookup: partial reconciliations
    /// landing on receivable/payable lines flip deferred (on_payment) tax
    /// pro-rata from the transition account onto the real tax account. Hosts
    /// without a tax module leave it unset — no flips, everything else works.
    pub fn with_deferred_tax(
        mut self,
        port: Arc<dyn crate::domain::repositories::DeferredTaxLookup>,
    ) -> Self {
        self.deferred_tax = Some(port);
        self
    }
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<AccountingModule> {
        let db_pool = self
            .db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Account service
        let account_repository = Arc::new(AccountRepository::new(db_pool.clone()));
        let account_service = Arc::new(AccountService::with_repository(account_repository.clone()));

        // AccountingPost service
        let accounting_post_repository = Arc::new(AccountingPostRepository::new(db_pool.clone()));
        let accounting_post_service = Arc::new(AccountingPostService::with_repository(
            accounting_post_repository.clone(),
        ));

        // CostCenter service
        let cost_center_repository = Arc::new(CostCenterRepository::new(db_pool.clone()));
        let cost_center_service = Arc::new(CostCenterService::with_repository(
            cost_center_repository.clone(),
        ));

        // FinancialStatement service
        let financial_statement_repository =
            Arc::new(FinancialStatementRepository::new(db_pool.clone()));
        let financial_statement_service = Arc::new(FinancialStatementService::with_repository(
            financial_statement_repository.clone(),
        ));

        // FiscalPeriod service
        let fiscal_period_repository = Arc::new(FiscalPeriodRepository::new(db_pool.clone()));
        let fiscal_period_service = Arc::new(FiscalPeriodService::with_repository(
            fiscal_period_repository.clone(),
        ));

        // Journal service
        let journal_repository = Arc::new(JournalRepository::new(db_pool.clone()));
        let journal_service = Arc::new(JournalService::with_repository(journal_repository.clone()));

        // JournalLine service
        let journal_line_repository = Arc::new(JournalLineRepository::new(db_pool.clone()));
        let journal_line_service = Arc::new(JournalLineService::with_repository(
            journal_line_repository.clone(),
        ));

        // Ledger service
        let ledger_repository = Arc::new(LedgerRepository::new(db_pool.clone()));
        let ledger_service = Arc::new(LedgerService::with_repository(ledger_repository.clone()));

        // Reconciliation service
        let reconciliation_repository = Arc::new(ReconciliationRepository::new(db_pool.clone()));
        let reconciliation_service = Arc::new(ReconciliationService::with_repository(
            reconciliation_repository.clone(),
        ));

        // ReconciliationItem service
        let reconciliation_item_repository =
            Arc::new(ReconciliationItemRepository::new(db_pool.clone()));
        let reconciliation_item_service = Arc::new(ReconciliationItemService::with_repository(
            reconciliation_item_repository.clone(),
        ));

        // FullReconcile service
        let full_reconcile_repository = Arc::new(FullReconcileRepository::new(db_pool.clone()));
        let full_reconcile_service = Arc::new(FullReconcileService::with_repository(
            full_reconcile_repository.clone(),
        ));

        // PartialReconcile service
        let partial_reconcile_repository =
            Arc::new(PartialReconcileRepository::new(db_pool.clone()));
        let partial_reconcile_service = Arc::new(PartialReconcileService::with_repository(
            partial_reconcile_repository.clone(),
        ));
        // <<< CUSTOM
        // Reconciliation write service: graph port + posting port (reversals of
        // generated moves) over the shared pool; no FX account by default (fail-closed).
        let reconcile_graph_repository = std::sync::Arc::new(
            crate::infrastructure::persistence::reconcile_graph_repository::SqlxReconcileGraphRepository::new(),
        );
        let reconcile_posting_repository = std::sync::Arc::new(
            crate::infrastructure::persistence::posting_repository::SqlxPostingRepository::new(
                db_pool.clone(),
            ),
        );
        let reconcile_write_service = std::sync::Arc::new(
            crate::application::service::reconcile_write_service::ReconcileWriteService::new(
                reconcile_graph_repository,
                reconcile_posting_repository,
                db_pool.clone(),
                None,
            )
            .with_deferred_tax_if_set(self.deferred_tax.clone()),
        );
        // Chart install engine: datasets registered by the host drive idempotent
        // chart installs onto fresh companies (provenance columns identify own rows).
        let chart_install_service = std::sync::Arc::new(
            crate::application::service::chart_install_service::ChartInstallService::new(
                std::sync::Arc::new(
                    crate::infrastructure::persistence::chart_install_repository::SqlxChartInstallRepository::new(),
                ),
                db_pool.clone(),
                self.chart_datasets,
            ),
        );
        // END CUSTOM

        // <<< CUSTOM
        // END CUSTOM

        Ok(AccountingModule {
            account_service,
            accounting_post_service,
            cost_center_service,
            financial_statement_service,
            fiscal_period_service,
            journal_service,
            journal_line_service,
            ledger_service,
            reconciliation_service,
            reconciliation_item_service,
            full_reconcile_service,
            partial_reconcile_service,
            // <<< CUSTOM
            db_pool,
            reconcile_write_service,
            deferred_tax: self.deferred_tax,
            chart_install_service,
            // END CUSTOM
        })
    }
}

impl Default for AccountingModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
