//! Accounting Module
//!
//! Generated by backbone-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AccountService;
pub use application::service::AccountingPostService;
pub use application::service::FinancialStatementService;
pub use application::service::FiscalPeriodService;
pub use application::service::JournalService;
pub use application::service::JournalLineService;
pub use application::service::LedgerService;
pub use application::service::ReconciliationService;
pub use application::service::ReconciliationItemService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Accounting module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let accounting = AccountingModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// let router = accounting.routes();
/// ```
pub struct AccountingModule {
    pub account_service: Arc<AccountService>,
    pub accounting_post_service: Arc<AccountingPostService>,
    pub financial_statement_service: Arc<FinancialStatementService>,
    pub fiscal_period_service: Arc<FiscalPeriodService>,
    pub journal_service: Arc<JournalService>,
    pub journal_line_service: Arc<JournalLineService>,
    pub ledger_service: Arc<LedgerService>,
    pub reconciliation_service: Arc<ReconciliationService>,
    pub reconciliation_item_service: Arc<ReconciliationItemService>,
}

impl AccountingModule {
    /// Create a new module builder
    pub fn builder() -> AccountingModuleBuilder {
        AccountingModuleBuilder::new()
    }

    /// Configure HTTP routes for this module using Axum
    ///
    /// Returns an Axum Router with all 12 Backbone CRUD endpoints per entity.
    pub fn routes(&self) -> Router {
        use presentation::http::{
            create_account_routes,
            create_accounting_post_routes,
            create_financial_statement_routes,
            create_fiscal_period_routes,
            create_journal_routes,
            create_journal_line_routes,
            create_ledger_routes,
            create_reconciliation_routes,
            create_reconciliation_item_routes,
        };

        Router::new()
            .merge(create_account_routes(self.account_service.clone()))
            .merge(create_accounting_post_routes(self.accounting_post_service.clone()))
            .merge(create_financial_statement_routes(self.financial_statement_service.clone()))
            .merge(create_fiscal_period_routes(self.fiscal_period_service.clone()))
            .merge(create_journal_routes(self.journal_service.clone()))
            .merge(create_journal_line_routes(self.journal_line_service.clone()))
            .merge(create_ledger_routes(self.ledger_service.clone()))
            .merge(create_reconciliation_routes(self.reconciliation_service.clone()))
            .merge(create_reconciliation_item_routes(self.reconciliation_item_service.clone()))
    }
}

/// Builder for AccountingModule
pub struct AccountingModuleBuilder {
    db_pool: Option<PgPool>,
}

impl AccountingModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<AccountingModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Account service
        let account_repository = Arc::new(AccountRepository::new(db_pool.clone()));
        let account_service = Arc::new(AccountService::with_repository(account_repository.clone()));

        // AccountingPost service
        let accounting_post_repository = Arc::new(AccountingPostRepository::new(db_pool.clone()));
        let accounting_post_service = Arc::new(AccountingPostService::with_repository(accounting_post_repository.clone()));

        // FinancialStatement service
        let financial_statement_repository = Arc::new(FinancialStatementRepository::new(db_pool.clone()));
        let financial_statement_service = Arc::new(FinancialStatementService::with_repository(financial_statement_repository.clone()));

        // FiscalPeriod service
        let fiscal_period_repository = Arc::new(FiscalPeriodRepository::new(db_pool.clone()));
        let fiscal_period_service = Arc::new(FiscalPeriodService::with_repository(fiscal_period_repository.clone()));

        // Journal service
        let journal_repository = Arc::new(JournalRepository::new(db_pool.clone()));
        let journal_service = Arc::new(JournalService::with_repository(journal_repository.clone()));

        // JournalLine service
        let journal_line_repository = Arc::new(JournalLineRepository::new(db_pool.clone()));
        let journal_line_service = Arc::new(JournalLineService::with_repository(journal_line_repository.clone()));

        // Ledger service
        let ledger_repository = Arc::new(LedgerRepository::new(db_pool.clone()));
        let ledger_service = Arc::new(LedgerService::with_repository(ledger_repository.clone()));

        // Reconciliation service
        let reconciliation_repository = Arc::new(ReconciliationRepository::new(db_pool.clone()));
        let reconciliation_service = Arc::new(ReconciliationService::with_repository(reconciliation_repository.clone()));

        // ReconciliationItem service
        let reconciliation_item_repository = Arc::new(ReconciliationItemRepository::new(db_pool.clone()));
        let reconciliation_item_service = Arc::new(ReconciliationItemService::with_repository(reconciliation_item_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(AccountingModule {
            account_service,
            accounting_post_service,
            financial_statement_service,
            fiscal_period_service,
            journal_service,
            journal_line_service,
            ledger_service,
            reconciliation_service,
            reconciliation_item_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for AccountingModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
