//! Use case type aliases for AccountingPost aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAccountingPostDto, UpdateAccountingPostDto};
use crate::application::service::AccountingPostService;
use crate::domain::entity::AccountingPost;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAccountingPostUseCase = CreateUseCase<AccountingPost, CreateAccountingPostDto, AccountingPostService>;
pub type UpdateAccountingPostUseCase = UpdateUseCase<AccountingPost, UpdateAccountingPostDto, AccountingPostService>;
pub type GetAccountingPostUseCase    = GetUseCase<AccountingPost, AccountingPostService>;
pub type DeleteAccountingPostUseCase = DeleteUseCase<AccountingPost, AccountingPostService>;
pub type ListAccountingPostUseCase   = ListUseCase<AccountingPost, AccountingPostService>;

// <<< CUSTOM
// END CUSTOM
