//! Use case type aliases for Account aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAccountDto, UpdateAccountDto};
use crate::application::service::AccountService;
use crate::domain::entity::Account;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAccountUseCase = CreateUseCase<Account, CreateAccountDto, AccountService>;
pub type UpdateAccountUseCase = UpdateUseCase<Account, UpdateAccountDto, AccountService>;
pub type GetAccountUseCase    = GetUseCase<Account, AccountService>;
pub type DeleteAccountUseCase = DeleteUseCase<Account, AccountService>;
pub type ListAccountUseCase   = ListUseCase<Account, AccountService>;

// <<< CUSTOM
// END CUSTOM
