//! Use case type aliases for FiscalPeriod aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateFiscalPeriodDto, UpdateFiscalPeriodDto};
use crate::application::service::FiscalPeriodService;
use crate::domain::entity::FiscalPeriod;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateFiscalPeriodUseCase = CreateUseCase<FiscalPeriod, CreateFiscalPeriodDto, FiscalPeriodService>;
pub type UpdateFiscalPeriodUseCase = UpdateUseCase<FiscalPeriod, UpdateFiscalPeriodDto, FiscalPeriodService>;
pub type GetFiscalPeriodUseCase    = GetUseCase<FiscalPeriod, FiscalPeriodService>;
pub type DeleteFiscalPeriodUseCase = DeleteUseCase<FiscalPeriod, FiscalPeriodService>;
pub type ListFiscalPeriodUseCase   = ListUseCase<FiscalPeriod, FiscalPeriodService>;

// <<< CUSTOM
// END CUSTOM
