//! Use case type aliases for Journal aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateJournalDto, UpdateJournalDto};
use crate::application::service::JournalService;
use crate::domain::entity::Journal;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateJournalUseCase = CreateUseCase<Journal, CreateJournalDto, JournalService>;
pub type UpdateJournalUseCase = UpdateUseCase<Journal, UpdateJournalDto, JournalService>;
pub type GetJournalUseCase    = GetUseCase<Journal, JournalService>;
pub type DeleteJournalUseCase = DeleteUseCase<Journal, JournalService>;
pub type ListJournalUseCase   = ListUseCase<Journal, JournalService>;

// <<< CUSTOM
// END CUSTOM
