//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod account_handler;
pub mod accounting_post_handler;
pub mod cost_center_handler;
pub mod financial_statement_handler;
pub mod fiscal_period_handler;
pub mod journal_handler;
pub mod journal_line_handler;
pub mod ledger_handler;
pub mod reconciliation_handler;
pub mod reconciliation_item_handler;

// <<< CUSTOM
pub mod posting_handler;
pub mod reporting_handler;
pub mod accounting_ops_handler;
pub mod journal_workflow_handler;
pub mod hierarchy_handler;
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use account_handler::{create_account_routes, create_account_read_routes, create_account_write_routes};
pub use accounting_post_handler::{create_accounting_post_routes, create_accounting_post_read_routes, create_accounting_post_write_routes};
pub use cost_center_handler::{create_cost_center_routes, create_cost_center_read_routes, create_cost_center_write_routes};
pub use financial_statement_handler::{create_financial_statement_routes, create_financial_statement_read_routes, create_financial_statement_write_routes};
pub use fiscal_period_handler::{create_fiscal_period_routes, create_fiscal_period_read_routes, create_fiscal_period_write_routes};
pub use journal_handler::{create_journal_routes, create_journal_read_routes, create_journal_write_routes};
pub use journal_line_handler::{create_journal_line_routes, create_journal_line_read_routes, create_journal_line_write_routes};
pub use ledger_handler::{create_ledger_routes, create_ledger_read_routes, create_ledger_write_routes};
pub use reconciliation_handler::{create_reconciliation_routes, create_reconciliation_read_routes, create_reconciliation_write_routes};
pub use reconciliation_item_handler::{create_reconciliation_item_routes, create_reconciliation_item_read_routes, create_reconciliation_item_write_routes};
// <<< CUSTOM
pub use posting_handler::{create_posting_routes, PostingRequestDto, PostingLineDto, PostingResponse};
pub use reporting_handler::create_reporting_routes;
pub use accounting_ops_handler::{create_bank_reconciliation_routes, create_period_close_routes, ClosePeriodBody};
pub use journal_workflow_handler::create_journal_workflow_routes;
pub use hierarchy_handler::create_hierarchy_routes;
pub use guarded_routes::create_guarded_accounting_routes;
// END CUSTOM